import type { ComponentTokens } from "./theme.types";

export const components: ComponentTokens = {
    card: {
        rounded: "calc(var(--var-radius) + calc(var(--var-spacing-base) / 4))",
        "padding-x": "calc(var(--var-spacing-base) * 1.5)",
        "padding-y": "calc(var(--var-spacing-base) * 0.75)",
        gap: "calc(var(--var-spacing-base) * 1)",
        "title-pb": "calc(var(--var-spacing-base) / 2)",
        "title-mb": "calc(var(--var-spacing-base) / 2)",
        "stats-icon-col-w": "calc(var(--var-spacing-base) * 5)",
        "stats-icon-col-p": "calc(var(--var-spacing-base) * 1)",
        "stats-icon-size": "calc(var(--var-spacing-base) * 3)",
        "stats-content-gap": "calc(var(--var-spacing-base) / 2)",
        "stats-content-py": "calc(var(--var-spacing-base) / 2)",
        "title-text": "calc(var(--var-fontsize) * 1.25)",
    },
    button: {
        "height-big": "calc(var(--var-spacing-base) * 3)",
        "height-min": "calc(var(--var-spacing-base) * 1.75)",
        "height-small": "calc(var(--var-spacing-base) * 2)",
        "height-tiny": "calc(var(--var-spacing-base) * 1.5)",
        "padding-icon": "calc(var(--var-spacing-base) / 4)",
        "padding-x": "calc(var(--var-spacing-base) * 1)",
        "padding-x-big": "calc(var(--var-spacing-base) * 1.5)",
        "padding-x-min": "calc(var(--var-spacing-base) * 0.75)",
        "padding-x-small": "calc(var(--var-spacing-base) * 1)",
        "padding-x-tiny": "calc(var(--var-spacing-base) / 2)",
        "padding-y": "calc(var(--var-spacing-base) / 2)",
        "padding-y-big": "calc(var(--var-spacing-base) * 1)",
        "padding-y-min": "calc(var(--var-spacing-base) / 4)",
        "padding-y-small": "calc(var(--var-spacing-base) / 2)",
        "padding-y-tiny": "calc(var(--var-spacing-base) / 4)",
        "radius-rough": "calc(var(--var-radius) / 6)",
        "radius-squared": "0",
        "text-big": "calc(var(--var-fontsize) * 1)",
        "text-icon": "calc(var(--var-fontsize) * 1)",
        "text-min": "calc(var(--var-fontsize) * 0.875)",
        "text-small": "calc(var(--var-fontsize) * 0.875)",
        "text-tiny": "calc(var(--var-fontsize) * 0.875)",
        gap: "calc(var(--var-spacing-base) * 0.375)",
        height: "calc(var(--var-spacing-base) * 2.5)",
        rounded: "calc(var(--var-radius) * 0.733333)",
        text: "calc(var(--var-fontsize) * 1)",
    },
    alert: {
        rounded: "calc(var(--var-radius) - calc(var(--var-spacing-base) / 4))",
        p: "calc(var(--var-spacing-base) * 1)",
        gap: "calc(var(--var-spacing-base) / 2)",
        "close-top": "calc(var(--var-spacing-base) * 0.75)",
        "close-right": "calc(var(--var-spacing-base) * 0.75)",
    },
    modal: {
        "surface-min-inline-size": "calc(var(--var-spacing-base) * 20)",
        "surface-gap": "calc(var(--var-spacing-base) * 1)",
        "surface-radius": "calc(var(--var-radius) * 1.333333)",
        "surface-padding-block": "calc(var(--var-spacing-base) * 1.5)",
        "dialog-max-inline-size-mobile": "calc(var(--var-spacing-base) * 20)",
        "dialog-max-block-size": "calc(var(--var-spacing-base) * 40)",
        "sheet-max-block-size": "90svh",
        "sheet-padding-block-start": "calc(var(--var-spacing-base) * 1.5)",
        "sheet-padding-block-end": "calc(var(--var-spacing-base) * 1.5)",
        "resizer-radius": "calc(var(--var-radius) * 0.666667)",
        "focus-outline-offset": "calc(var(--var-spacing-base) * 0.125)",
        "resizer-focus-ring-width": "calc(var(--var-spacing-base) / 4)",
        "sheet-handle-inset-block-start": "calc(var(--var-spacing-base) / 4)",
        "sheet-handle-block-size": "calc(var(--var-spacing-base) * 1)",
        "sheet-handle-padding-block": "calc(var(--var-spacing-base) / 4)",
        "drawer-resizer-inset-inline": "calc(var(--var-spacing-base) * 1.25)",
        "drawer-resizer-inset-inline-start": "calc(var(--var-spacing-base) * 0.5)",
        "drawer-resizer-block-size": "calc(var(--var-spacing-base) * 4)",
        "drawer-resizer-inline-size": "calc(var(--var-spacing-base) * 0.5)",
        "sheet-pill-block-size": "calc(var(--var-spacing-base) * 0.25)",
        "sheet-pill-inline-size": "calc(var(--var-spacing-base) * 4)",
        "overlay-block-size": "100vh",
        "overlay-padding-block-start": "calc(var(--var-spacing-base) * 1.5)",
        "content-padding-inline": "calc(var(--var-spacing-base) * 1.5)",
        "title-padding-block-end": "calc(var(--var-spacing-base) * 1)",
        "title-font-size": "calc(var(--var-fontsize) * 1.25)",
        "title-line-height": "1.625",
        "body-padding-block": "calc(var(--var-spacing-base) * 1)",
        "footer-padding-block-start": "calc(var(--var-spacing-base) * 1)",
        "close-inset-inline-end": "calc(var(--var-spacing-base) * 1)",
        "close-inset-block-start": "calc(var(--var-spacing-base) * 1)",
        "close-button-padding": "calc(var(--var-spacing-base) * 0.5)",
        "close-button-opacity": "0.7",
        "transition-duration": "375ms",
        "transition-timing": "cubic-bezier(0, 0, 0.58, 1)",
        "close-focus-ring-width": "calc(var(--var-spacing-base) * 0.125)",
        "close-icon-size": "calc(var(--var-fontsize) * 1.25)",
        "confirm-dialog-max-inline-size": "calc(var(--var-spacing-base) * 24)",
        "confirm-actions-gap": "calc(var(--var-spacing-base) * 1)",
        "confirm-description-padding-block": "calc(var(--var-spacing-base) * 1)",
        "overlay-background": "hsla(240, 6%, 10%, 0.8)",
    },
    dropdown: {
        "surface-radius": "calc(var(--var-radius) + calc(var(--var-spacing-base) / 2))",
        "surface-padding": "calc(var(--var-spacing-base) * 1)",
        "header-margin-block-end": "calc(var(--var-spacing-base) / 2)",
        "title-font-size": "calc(var(--var-fontsize) * 1.5)",
        "title-letter-spacing": "0.025em",
        "list-max-block-size": "calc(var(--var-spacing-base) * 24)",
        "surface-background": "hsla(0, 0%, 100%)",
        "surface-border": "hsla(240, 6%, 90%)",
        "surface-foreground": "hsla(240, 10%, 4%)",
    },
    expand: {},
    tooltip: {
        "surface-radius": "calc(var(--var-radius) + calc(var(--var-spacing-base) / 2))",
        "surface-padding": "calc(var(--var-spacing-base) * 0.75)",
        "surface-background": "hsla(240, 10%, 4%)",
        "surface-border": "hsla(240, 10%, 4%)",
        "surface-foreground": "hsla(0, 0%, 100%)",
    },
    menu: {
        "surface-radius": "calc(var(--var-radius) + calc(var(--var-spacing-base) / 2))",
        "surface-max-block-size": "calc(var(--var-spacing-base) * 20)",
        "surface-background": "hsla(0, 0%, 100%)",
        "surface-border": "hsla(240, 6%, 90%)",
        "surface-foreground": "hsla(240, 10%, 4%)",
        "item-padding": "calc(var(--var-spacing-base) * 0.625)",
        "item-min-inline-size": "calc(var(--var-spacing-base) * 9)",
        "item-outline-width": "calc(var(--var-spacing-base) * 0.125)",
        "item-outline-offset": "calc(var(--var-spacing-base) * 0.125)",
        "item-expanded-opacity": "0.8",
        "item-disabled-opacity": "0.4",
        "item-active-background": "hsla(201, 49%, 36%)",
        "item-active-foreground": "hsla(221, 6%, 90%)",
        "nested-indicator-margin-inline-start": "calc(var(--var-spacing-base) * 0.625)",
        "nested-indicator-font-size": "calc(var(--var-fontsize) * 0.625)",
        "nested-icon-size": "calc(var(--var-fontsize) * 0.875)",
        "item-icon-size": "calc(var(--var-fontsize) * 1)",
    },
    stats: {
        rounded: "1rem",
        p: "1.5rem",
        gap: "1rem",
        "icon-size": "2.5rem",
        "icon-p": "2rem",
        "inner-gap": "0.25rem",
        "title-text": "1rem",
        "value-text": "2.25rem",
        "footer-px": "1.5rem",
        "footer-py": "0.5rem",
    },
    notification: {
        rounded: "calc(var(--var-radius) * 1.333333)",
        p: "calc(var(--var-spacing-base) * 1)",
        gap: "calc(var(--var-spacing-base) * 0.75)",
        "inner-gap": "calc(var(--var-spacing-base) * 0.25)",
        "close-p": "calc(var(--var-spacing-base) * 0.25)",
        "close-radius": "calc(var(--var-radius) * 0.666667)",
        "list-gap": "calc(var(--var-spacing-base) * 0.75)",
        "badge-px": "calc(var(--var-spacing-base) * 0.75)",
        "badge-py": "calc(var(--var-spacing-base) * 0.25)",
        "list-top": "calc(var(--var-spacing-base) * 1)",
        "list-max-w": "calc(var(--var-spacing-base) * 28)",
        "badge-text": "calc(var(--var-fontsize) * 0.75)",
    },
    command: {
        "surface-background": "hsla(0, 0%, 100%)",
        "surface-border": "hsla(240, 6%, 90%)",
        "surface-foreground": "hsla(240, 10%, 4%)",
        "dialog-max-inline-size-md": "calc(var(--var-spacing-base) * 40)",
        "dialog-max-inline-size-lg": "calc(var(--var-spacing-base) * 48)",
        "row-block-size": "calc(var(--var-spacing-base) * 2.5)",
        "header-block-size": "calc(var(--var-spacing-base) * 3)",
        "footer-block-size": "calc(var(--var-spacing-base) * 2)",
        "footer-padding": "calc(var(--var-spacing-base) * 0.5)",
        "list-max-block-size": "calc(var(--var-spacing-base) * 24)",
        "list-gap": "calc(var(--var-spacing-base) * 0.25)",
        "list-margin-block": "calc(var(--var-spacing-base) * 0.5)",
        "list-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
        "group-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
        "group-padding-block-start": "calc(var(--var-spacing-base) * 0.5)",
        "group-padding-block-end": "calc(var(--var-spacing-base) * 0.25)",
        "group-label-foreground": "hsla(240, 6%, 10%)",
        "item-radius": "calc(var(--var-radius) + calc(var(--var-spacing-base) / 2))",
        "item-padding": "calc(var(--var-spacing-base) * 0.5)",
        "item-content-gap": "calc(var(--var-spacing-base) * 0.5)",
        "item-background-hover": "hsla(240, 5%, 96%)",
        "search-icon-frame-size": "calc(var(--var-spacing-base) * 2.5)",
        "search-icon-size": "calc(var(--var-fontsize) * 1)",
        "input-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
        "input-padding-block": "calc(var(--var-spacing-base) * 0.5)",
        "input-outline-width": "calc(var(--var-spacing-base) * 0.125)",
        "input-outline-offset": "calc(var(--var-spacing-base) * 0.125)",
        "empty-foreground": "hsla(240, 6%, 10%)",
    },
    tag: {
        "surface-gap": "calc(var(--var-spacing-base) * 0.375)",
        "surface-radius": "calc(var(--var-radius) * 2.666667)",
        "default-min-block-size": "calc(var(--var-spacing-base) * 2)",
        "default-padding-inline": "calc(var(--var-spacing-base) * 1)",
        "default-padding-block": "calc(var(--var-spacing-base) * 0.5)",
        "big-min-block-size": "calc(var(--var-spacing-base) * 3)",
        "big-padding-inline": "calc(var(--var-spacing-base) * 1.5)",
        "big-padding-block": "calc(var(--var-spacing-base) * 1)",
        "small-min-block-size": "calc(var(--var-spacing-base) * 1.5)",
        "small-padding-inline": "calc(var(--var-spacing-base) * 0.75)",
        "small-padding-block": "calc(var(--var-spacing-base) * 0.5)",
        "small-font-size": "calc(var(--var-fontsize) * 0.875)",
        "tiny-min-block-size": "calc(var(--var-spacing-base) * 1.25)",
        "tiny-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
        "tiny-padding-block": "calc(var(--var-spacing-base) * 0.25)",
        "tiny-font-size": "calc(var(--var-fontsize) * 0.75)",
        "icon-padding": "calc(var(--var-spacing-base) * 0.25)",
        "indicator-size": "calc(var(--var-spacing-base) * 0.5)",
    },
    calendar: {
        "cell-p": "calc(var(--var-spacing-base) / 4)",
        "day-size": "calc(var(--var-spacing-base) * 2.25)",
        "nav-p": "calc(var(--var-spacing-base) / 4)",
        "weekday-py": "calc(var(--var-spacing-base) * 0.5)",
        "table-mt": "calc(var(--var-spacing-base) * 1)",
        "datetime-my": "calc(var(--var-spacing-base) * 1)",
        "footer-mt": "calc(var(--var-spacing-base) * 1)",
        "header-radius": "calc(var(--var-radius) * 0.733333)",
        "nav-gap": "calc(var(--var-spacing-base) * 0.5)",
        "nav-py": "calc(var(--var-spacing-base) / 4)",
        "year-w": "calc(var(--var-spacing-base) * 4)",
        "icon-size": "calc(var(--var-fontsize) * 1)",
        "weekday-text": "calc(var(--var-fontsize) * 0.75)",
        "cell-text": "calc(var(--var-fontsize) * 0.75)",
    },
    table: {
        rounded: "calc(var(--var-radius) * 0.666667)",
        "groups-gap": "calc(var(--var-spacing-base) * 1)",
        "inline-gap-tight": "calc(var(--var-spacing-base) * 0.25)",
        "filter-gap": "calc(var(--var-spacing-base) * 1)",
        "filter-row-gap": "calc(var(--var-spacing-base) * 0.75)",
        "filter-inline-gap": "calc(var(--var-spacing-base) * 1)",
        "filter-inline-padding-block": "calc(var(--var-spacing-base) * 0.5)",
        "filter-list-margin-block-start": "calc(var(--var-spacing-base) * 1)",
        "groups-margin-block-start": "calc(var(--var-spacing-base) * 1)",
        "groups-margin-block": "calc(var(--var-spacing-base) * 1)",
        "row-gap": "calc(var(--var-spacing-base) * 0.25)",
        "row-padding-block-end": "calc(var(--var-spacing-base) * 1)",
        "cell-padding": "calc(var(--var-spacing-base) * 0.75)",
        "cell-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
        "cell-border": "calc(var(--var-border-hairline) * 1)",
        "head-cell-block-size": "calc(var(--var-spacing-base) * 3.5)",
        "divider-width": "calc(var(--var-border-hairline) * 1)",
        "pagination-padding": "calc(var(--var-spacing-base) * 0.75)",
        "pagination-gap": "calc(var(--var-spacing-base) * 1)",
        "pagination-items-gap": "calc(var(--var-spacing-base) * 0.5)",
        "pagination-item-padding-inline": "calc(var(--var-spacing-base) * 0.75)",
        "pagination-item-padding-block": "calc(var(--var-spacing-base) * 0.25)",
        "metadata-margin-block-end": "calc(var(--var-spacing-base) * 0.25)",
        "metadata-gap-inline": "calc(var(--var-spacing-base) * 1)",
        "metadata-gap-block": "calc(var(--var-spacing-base) * 0.25)",
        "metadata-min-inline-size": "1ch",
        "operations-padding-block": "calc(var(--var-spacing-base) * 0.5)",
        "operations-gap": "calc(var(--var-spacing-base) * 1)",
        "pill-radius": "calc(var(--var-radius) * 1)",
        "pill-padding-inline": "calc(var(--var-spacing-base) * 1)",
        "pill-padding-block": "calc(var(--var-spacing-base) * 0.125)",
        "filter-dot-size": "calc(var(--var-spacing-base) * 0.75)",
        "filter-dot-margin-inline-end": "calc(var(--var-spacing-base) * 0.5)",
        "loading-block-size": "calc(var(--var-spacing-base) * 3.5)",
        "loading-bar-block-size": "calc(var(--var-spacing-base) * 0.5)",
        "loading-bar-radius": "calc(var(--var-radius) / 3)",
        "empty-block-size": "calc(var(--var-spacing-base) * 12)",
    },
    skeleton: {
        rounded: "calc(var(--var-radius) / 3)",
        height: "calc(var(--var-spacing-base) * 2)",
        width: "calc(var(--var-spacing-base) * 8)",
        "cell-h": "calc(var(--var-spacing-base) * 1.5)",
        "list-gap": "calc(var(--var-spacing-base) * 1.5)",
    },
    typography: {
        xs: "calc(var(--var-fontsize) * 0.75)",
        sm: "var(--var-typography-sm)",
        base: "var(--var-typography-paragraph-font-size)",
        lg: "var(--var-typography-lg)",
        xl: "var(--var-typography-xl)",
        "2xl": "var(--var-typography-page-title-font-size)",
        "3xl": "calc(var(--var-fontsize) * 2.25)",
        "4xl": "calc(var(--var-fontsize) * 3)",
        "5xl": "calc(var(--var-fontsize) * 3.75)",
    },
    input: {
        "field-icon-size": "calc(var(--var-fontsize) * 1)",
        "field-small-icon-size": "calc(var(--var-fontsize) * 0.875)",
        "field-label-row-gap": "calc(var(--var-spacing-base) * 0.25)",
        "field-label-meta-gap": "calc(var(--var-spacing-base) * 0.25)",
        "field-tooltip-icon-size": "calc(var(--var-fontsize) * 0.75)",
        "field-small-tooltip-icon-size": "calc(var(--var-fontsize) * 0.6875)",
        "field-tooltip-max-inline-size": "calc(var(--var-spacing-base) * 12)",
        "field-status-min-inline-size": "calc(var(--var-spacing-base) * 1.5)",
        "field-small-status-min-inline-size": "calc(var(--var-spacing-base) * 1.25)",
        "field-status-block-size": "calc(var(--var-spacing-base) * 0.75)",
        "field-small-status-block-size": "calc(var(--var-spacing-base) * 0.625)",
        "field-status-indicator-size": "calc(var(--var-spacing-base) * 0.75)",
        "field-small-status-indicator-size": "calc(var(--var-spacing-base) * 0.625)",
        "field-label-gap": "calc(var(--var-spacing-base) * 0.25)",
        "field-label-font-size": "calc(var(--var-fontsize) * 0.875)",
        "field-small-label-font-size": "calc(var(--var-fontsize) * 0.75)",
        "field-optional-opacity": "0.7",
        "field-control-column-gap": "calc(var(--var-spacing-base) * 0.5)",
        "field-small-control-column-gap": "calc(var(--var-spacing-base) * 0.375)",
        "field-control-row-gap": "calc(var(--var-spacing-base) * 0.25)",
        "field-small-control-row-gap": "calc(var(--var-spacing-base) * 0.25)",
        "field-control-radius": "calc(var(--var-radius) * 0.375)",
        "field-slot-gap": "calc(var(--var-spacing-base) * 0.5)",
        "field-small-slot-gap": "calc(var(--var-spacing-base) * 0.375)",
        "field-slot-padding-inline-start": "calc(var(--var-spacing-base) * 0.5)",
        "field-small-slot-padding-inline-start": "calc(var(--var-spacing-base) * 0.375)",
        "field-slot-padding-inline-end": "calc(var(--var-spacing-base) * 0.5)",
        "field-small-slot-padding-inline-end": "calc(var(--var-spacing-base) * 0.375)",
        "field-hint-margin-block-start": "calc(var(--var-spacing-base) * 0.3)",
        "field-hint-font-size": "calc(var(--var-fontsize) * 0.75)",
        "field-small-hint-font-size": "calc(var(--var-fontsize) * 0.6875)",
        "free-text-control-height": "calc(var(--var-spacing-base) * 2.5)",
        "free-text-small-control-height": "calc(var(--var-spacing-base) * 2)",
        "free-text-surface-radius": "calc(var(--var-radius) * 0.375)",
        "free-text-surface-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
        "free-text-small-surface-padding-inline": "calc(var(--var-spacing-base) * 0.375)",
        "free-text-surface-padding-block": "calc(var(--var-spacing-base) * 0.25)",
        "free-text-small-surface-padding-block": "calc(var(--var-spacing-base) * 0.125)",
        "free-text-font-size": "calc(var(--var-fontsize) * 1)",
        "free-text-small-font-size": "calc(var(--var-fontsize) * 0.875)",
        "free-text-outline-width": "calc(var(--var-spacing-base) * 0.125)",
        "free-text-outline-offset": "calc(var(--var-spacing-base) * 0.125)",
        "free-text-placeholder-foreground": "hsla(240, 4%, 46%)",
        "free-text-error-placeholder-foreground": "hsla(0, 84%, 96%)",
    },
    autocomplete: {
        "list-max-block-size": "calc(var(--var-spacing-base) * 24)",
        "panel-radius": "calc(var(--var-radius) + calc(var(--var-spacing-base) / 2))",
        "option-min-block-size": "calc(var(--var-spacing-base) * 2.5)",
        "option-padding": "calc(var(--var-spacing-base) * 0.625)",
        "option-background-hover": "hsla(240, 5%, 96%)",
        "option-active-background": "hsla(201, 49%, 22%)",
        "option-active-foreground": "hsla(221, 6%, 90%)",
        "option-selected-background": "hsla(240, 5%, 96%)",
        "option-selected-foreground": "hsla(240, 10%, 4%)",
        "actions-gap": "calc(var(--var-spacing-base) * 0.125)",
        "action-padding": "calc(var(--var-spacing-base) * 0.5)",
        "action-padding-md": "calc(var(--var-spacing-base) * 0.25)",
        "panel-max-block-size": "calc(var(--var-spacing-base) * 20)",
        "panel-background": "hsla(0, 0%, 100%)",
        "panel-border": "hsla(240, 6%, 90%)",
        "panel-foreground": "hsla(221, 15%, 23%)",
        "panel-transition-timing": "cubic-bezier(0.4, 0, 0.2, 1)",
        "empty-border": "hsla(240, 10%, 4%)",
        "empty-foreground": "hsla(240, 5%, 96%)",
    },
    "multi-select": {
        "field-min-inline-size": "calc(var(--var-spacing-base) * 12)",
        "tag-remove-icon-size": "calc(var(--var-fontsize) * 0.875)",
        "tags-gap": "calc(var(--var-spacing-base) * 0.5)",
        "actions-gap": "calc(var(--var-spacing-base) * 0.125)",
        "panel-transition-timing": "cubic-bezier(0.4, 0, 0.2, 1)",
        "search-margin-block-end": "calc(var(--var-spacing-base) * 0.25)",
        "option-padding": "calc(var(--var-spacing-base) * 0.625)",
        "results-max-block-size": "calc(var(--var-spacing-base) * 18)",
        "option-background-hover": "hsla(240, 5%, 96%)",
        "option-selected-background": "hsla(240, 5%, 96%)",
        "option-selected-foreground": "hsla(240, 10%, 4%)",
        "checkbox-margin-inline-end": "calc(var(--var-spacing-base) * 0.5)",
        "footer-gap": "calc(var(--var-spacing-base) * 0.5)",
    },
    checkbox: {
        "label-gap": "calc(var(--var-spacing-base) * 0.5)",
        "control-size": "calc(var(--var-spacing-base) * 1)",
        "control-radius": "calc(var(--var-radius) * 0.25)",
        "control-foreground": "hsla(201, 49%, 36%)",
        "control-background": "hsla(0, 0%, 100%)",
        "control-border": "hsla(240, 6%, 90%)",
        "control-border-width": "calc(var(--var-spacing-base) * 0.0625)",
        "mark-foreground": "hsla(0, 0%, 100%)",
        "mark-stroke-width": "calc(var(--var-spacing-base) * 0.125)",
        "mark-inline-size": "calc(var(--var-spacing-base) * 0.35)",
        "mark-block-size": "calc(var(--var-spacing-base) * 0.6)",
        "indeterminate-mark-inline-size": "calc(var(--var-spacing-base) * 0.55)",
        "focus-ring": "hsla(201, 49%, 36%)",
        "focus-ring-width": "calc(var(--var-spacing-base) * 0.125)",
        "focus-ring-offset": "calc(var(--var-spacing-base) * 0.125)",
        "disabled-opacity": "0.7",
        "error-font-size": "calc(var(--var-fontsize) * 0.75)",
    },
    "date-picker": {
        "calendar-icon-size": "calc(var(--var-fontsize) * 1)",
        "panel-gap": "calc(var(--var-spacing-base) * 1)",
        "panel-padding": "calc(var(--var-spacing-base) * 1)",
        "presets-inline-size": "calc(var(--var-spacing-base) * 13)",
        "preset-padding-block": "calc(var(--var-spacing-base) * 0.625)",
        "preset-padding-inline": "calc(var(--var-spacing-base) * 0.875)",
        "preset-selected-background": "hsla(212, 100%, 96%)",
        "preset-font-size": "calc(var(--var-fontsize) * 0.875)",
        "action-button-padding-block": "calc(var(--var-spacing-base) * 0.625)",
        "action-button-padding-inline": "calc(var(--var-spacing-base) * 1)",
    },
    radiobox: {
        "label-gap": "calc(var(--var-spacing-base) * 0.5)",
        "control-size": "calc(var(--var-spacing-base) * 1)",
        "control-foreground": "hsla(201, 49%, 36%)",
        "control-background": "hsla(0, 0%, 100%)",
        "control-border": "hsla(240, 6%, 90%)",
        "control-border-width": "calc(var(--var-spacing-base) * 0.0625)",
        "mark-size": "calc(var(--var-spacing-base) * 0.375)",
        "mark-foreground": "hsla(0, 0%, 100%)",
        "focus-ring": "hsla(201, 49%, 36%)",
        "focus-ring-width": "calc(var(--var-spacing-base) * 0.125)",
        "focus-ring-offset": "calc(var(--var-spacing-base) * 0.125)",
        "disabled-opacity": "0.7",
        "transition-duration": "180ms",
        "transition-timing": "cubic-bezier(0.23, 1, 0.32, 1)",
    },
    switch: {
        "track-h": "calc(var(--var-spacing-base) * 1.5)",
        "track-w": "calc(var(--var-spacing-base) * 2.75)",
        "thumb-size": "calc(var(--var-spacing-base) * 1.25)",
        gap: "calc(var(--var-spacing-base) * 0.75)",
        "label-text": "calc(var(--var-fontsize) * 0.875)",
        "hint-text": "calc(var(--var-fontsize) * 0.75)",
        "hint-mt": "calc(var(--var-spacing-base) * 0.25)",
    },
    slider: {
        "control-h": "calc(var(--var-spacing-base) * 1.25)",
        "track-h": "calc(var(--var-spacing-base) * 0.5)",
        "thumb-size": "calc(var(--var-spacing-base) * 1.25)",
    },
    "file-upload": {
        "surface-padding": "calc(var(--var-spacing-base) * 1.5)",
        "surface-radius": "calc(var(--var-spacing-base) * 0.5)",
        "content-gap": "calc(var(--var-spacing-base) * 1)",
        "thumb-size": "calc(var(--var-spacing-base) * 4)",
        "thumb-radius": "50%",
        "thumb-icon-size": "calc(var(--var-fontsize) * 1.75)",
        "file-icon-size": "calc(var(--var-spacing-base) * 3)",
        "remove-icon-size": "calc(var(--var-fontsize) * 1)",
        "idle-icon-size": "calc(var(--var-spacing-base) * 5)",
        "preview-button-margin": "calc(var(--var-spacing-base) * 0.5)",
        "item-border-width": "calc(var(--var-spacing-base) * 0.0625)",
        "actions-padding-block": "calc(var(--var-spacing-base) * 1)",
        "remove-button-size": "calc(var(--var-spacing-base) * 1.5)",
        "list-gap": "calc(var(--var-spacing-base) * 2)",
        "idle-icon-gap": "calc(var(--var-spacing-base) * 0.5)",
        "idle-copy-margin-block": "calc(var(--var-spacing-base) * 1)",
        "idle-copy-gap": "calc(var(--var-spacing-base) * 0.25)",
        "name-font-size": "calc(var(--var-fontsize) * 1.125)",
        "size-font-size": "calc(var(--var-fontsize) * 0.875)",
        "viewer-media-max-inline-size": "calc(var(--var-spacing-base) * 24)",
    },
    progress: {
        "track-h": "calc(var(--var-spacing-base) * 1.5)",
        rounded: "calc(var(--var-radius) * 0.4)",
    },
    spinner: {
        "indicator-size": "calc(var(--var-spacing-base) * 3)",
        "indicator-border-width": "calc(var(--var-spacing-base) * 0.25)",
        "container-padding": "calc(var(--var-spacing-base) * 3)",
        "spin-duration": "1s",
    },
    empty: {
        gap: "calc(var(--var-spacing-base) * 1)",
        px: "calc(var(--var-spacing-base) * 2)",
        py: "calc(var(--var-spacing-base) * 3)",
    },
    list: {
        rounded: "calc(var(--var-radius) * 1.333333)",
        "card-p": "calc(var(--var-spacing-base) * 1.5)",
        "card-py": "calc(var(--var-spacing-base) * 1.5)",
        "card-pb": "calc(var(--var-spacing-base) * 1.5)",
        "card-gap": "calc(var(--var-spacing-base) * 1)",
        "close-p": "calc(var(--var-spacing-base) * 0.5)",
        "header-gap": "calc(var(--var-spacing-base) * 1)",
        "item-py": "calc(var(--var-spacing-base) * 1)",
        "item-gap": "calc(var(--var-spacing-base) * 1)",
        "avatar-px": "calc(var(--var-spacing-base) * 0.5)",
        "body-py": "calc(var(--var-spacing-base) * 0.5)",
        "title-text": "calc(var(--var-fontsize) * 1)",
    },
    timeline: {
        "item-padding-block-end": "calc(var(--var-spacing-base) * 2)",
        "connector-inset-inline-start": "calc(var(--var-spacing-base) * 1.5)",
        "connector-inset-block-start": "calc(var(--var-spacing-base) * 2)",
        "connector-inline-size": "calc(var(--var-border-hairline) * 2)",
        "content-gap": "calc(var(--var-spacing-base) * 0.75)",
        "icon-size": "calc(var(--var-spacing-base) * 2)",
        "icon-padding": "calc(var(--var-spacing-base) * 0.5)",
        "actions-gap": "calc(var(--var-spacing-base) * 1.5)",
        "actions-padding-inline": "calc(var(--var-spacing-base) * 1)",
    },
    step: {
        size: "calc(var(--var-spacing-base) * 2.5)",
        "icon-size": "calc(var(--var-fontsize) * 1.5)",
        "label-px": "calc(var(--var-spacing-base) * 0.5)",
        gap: "calc(var(--var-spacing-base) * 1)",
        "connector-h": "calc(var(--var-border-hairline) * 2)",
    },
    tabs: {
        "header-margin-block-end": "calc(var(--var-spacing-base) * 0.5)",
        "tab-padding-inline": "calc(var(--var-spacing-base) * 2.5)",
        "tab-padding-block": "calc(var(--var-spacing-base) * 1)",
        "divider-block-size": "calc(var(--var-border-hairline) * 1)",
        "active-divider-block-size": "calc(var(--var-border-hairline) * 2)",
        "item-transition-duration": "375ms",
    },
    shortcut: {
        gap: "calc(var(--var-spacing-base) * 0.25)",
        text: "calc(var(--var-fontsize) * 0.875)",
    },
    toolbar: {
        bottom: "calc(var(--var-spacing-base) * 1)",
        rounded: "calc(var(--var-spacing-base) * 0.5)",
        p: "calc(var(--var-spacing-base) * 1)",
    },
    wizard: {
        "surface-inline-size": "calc(var(--var-spacing-base) * 20)",
        "surface-max-inline-size": "calc(var(--var-spacing-base) * 24)",
        "surface-gap": "calc(var(--var-spacing-base) * 0.75)",
        "surface-radius": "calc(var(--var-radius) + calc(var(--var-spacing-base) / 2))",
        "surface-padding": "calc(var(--var-spacing-base) * 1)",
        "surface-background": "hsla(0, 0%, 100%)",
        "surface-border": "hsla(240, 6%, 90%)",
        "surface-foreground": "hsla(240, 10%, 4%)",
        "overlay-background": "hsla(240, 10%, 4%, 0.7)",
        "footer-padding-block-start": "calc(var(--var-spacing-base) * 0.5)",
        "label-font-size": "calc(var(--var-fontsize) * 0.75)",
        "label-foreground": "hsla(240, 4%, 46%)",
        "label-foreground-hover": "hsla(221, 15%, 23%)",
        "actions-gap": "calc(var(--var-spacing-base) * 0.5)",
        "counter-inset-inline-end": "calc(var(--var-spacing-base) * 0.5)",
        "counter-inset-block-start": "calc(var(--var-spacing-base) * 0.5)",
        "focus-outline-width": "calc(var(--var-spacing-base) * 0.125)",
        "focus-outline-offset": "calc(var(--var-spacing-base) * 0.125)",
    },
    info: {
        gap: "calc(var(--var-spacing-base) * 1)",
        "label-text": "calc(var(--var-fontsize) * 1)",
        "value-text": "calc(var(--var-fontsize) * 1)",
        "secondary-text": "calc(var(--var-fontsize) * 1)",
    },
    "page-calendar": {
        gap: "calc(var(--var-spacing-base) * 1)",
        "header-gap": "calc(var(--var-spacing-base) * 1)",
        "date-gap": "calc(var(--var-spacing-base) * 0.75)",
        "badge-size": "calc(var(--var-spacing-base) * 3)",
        "badge-radius": "calc(var(--var-radius) * 0.666667)",
        "title-text": "calc(var(--var-fontsize) * 1.25)",
        "week-label-text": "calc(var(--var-fontsize) * 0.75)",
        "nav-gap": "calc(var(--var-spacing-base) * 0.5)",
        "nav-button-gap": "calc(var(--var-spacing-base) * 0.25)",
        "today-radius": "calc(var(--var-radius) * 0.5)",
        "today-padding-inline": "calc(var(--var-spacing-base) * 0.75)",
        "today-padding-block": "calc(var(--var-spacing-base) * 0.375)",
        "today-font-size": "calc(var(--var-fontsize) * 0.875)",
        "view-switch-radius": "calc(var(--var-radius) * 0.5)",
        "filter-gap": "calc(var(--var-spacing-base) * 0.375)",
        "filter-font-size": "calc(var(--var-fontsize) * 0.75)",
        "dot-size": "calc(var(--var-spacing-base) * 0.25)",
        "dot-bottom": "calc(var(--var-spacing-base) * 0.125)",
        "day-header-gap": "calc(var(--var-spacing-base) * 0.75)",
        "day-header-padding-inline": "calc(var(--var-spacing-base) * 1)",
        "day-header-padding-block": "calc(var(--var-spacing-base) * 0.5)",
        "day-badge-size": "calc(var(--var-spacing-base) * 2)",
        "gutter-width": "calc(var(--var-spacing-base) * 3.75)",
        "side-padding-inline": "calc(var(--var-spacing-base) * 1)",
        "detail-gap": "calc(var(--var-spacing-base) * 0.5)",
        "detail-padding": "calc(var(--var-spacing-base) * 0.75)",
        "weekday-padding-block": "calc(var(--var-spacing-base) * 0.5)",
        "weekday-font-size": "calc(var(--var-fontsize) * 0.75)",
        "cell-min-block-size": "calc(var(--var-spacing-base) * 8)",
        "cell-gap": "calc(var(--var-spacing-base) * 0.25)",
        "cell-padding": "calc(var(--var-spacing-base) * 0.5)",
        "month-badge-size": "calc(var(--var-spacing-base) * 1.5)",
        "month-badge-font-size": "calc(var(--var-fontsize) * 0.75)",
        "overflow-font-size": "calc(var(--var-fontsize) * 1.125)",
        "week-badge-size": "calc(var(--var-spacing-base) * 1.5)",
        "week-badge-font-size": "calc(var(--var-fontsize) * 0.875)",
        "hour-font-size": "calc(var(--var-fontsize) * 0.625)",
        "pill-radius": "calc(var(--var-radius) / 3)",
        "pill-font-size": "calc(var(--var-fontsize) * 0.75)",
        "cell-gap-tight": "calc(var(--var-spacing-base) * 0.125)",
        "filter-label-margin-inline-end": "calc(var(--var-spacing-base) * 0.25)",
    },
};
