import { ComponentTokens } from "./theme.types";

export const components: ComponentTokens = {
    card: {
        radius: "1rem",
        "padding-x": "1.5rem",
        "padding-y": "0.75rem",
        gap: "1rem",
        "title-pb": "0.5rem",
        "title-mb": "0.5rem",
        "stats-icon-col-w": "5rem",
        "stats-icon-col-p": "1rem",
        "stats-content-gap": "0.5rem",
        "stats-content-py": "0.5rem",
    },
    button: {
        radius: "0.55rem",
        height: "2.5rem",
        "padding-x": "1rem",
        "padding-y": "0.5rem",
        gap: "0.375rem",
        "height-big": "3rem",
        "padding-x-big": "1.5rem",
        "padding-y-big": "1rem",
        "height-small": "2rem",
        "padding-x-small": "1rem",
        "padding-y-small": "0.5rem",
        "height-min": "1.75rem",
        "padding-x-min": "0.75rem",
        "padding-y-min": "0.25rem",
        "height-tiny": "1.5rem",
        "padding-x-tiny": "0.5rem",
        "padding-y-tiny": "0.25rem",
        "padding-icon": "0.25rem",
    },
    alert: {
        radius: "0.5rem",
        p: "1rem",
        gap: "0.5rem",
        "close-top": "0.75rem",
        "close-right": "0.75rem",
    },
    modal: {
        radius: "0.5rem",
        "padding-x": "2rem",
        "padding-y": "1rem",
        gap: "1rem",
        "title-pb": "0.5rem",
        "body-py": "0.25rem",
        "footer-pt": "1rem",
        "footer-gap": "0.5rem",
        "sheet-pt": "1.5rem",
        "sheet-pb": "1rem",
        "close-p": "0.25rem",
        "close-top": "0.25rem",
        "close-right": "1rem",
        "confirm-py": "0.5rem",
        "sheet-handle-h": "0.75rem",
        "sheet-handle-py": "0.5rem",
        "sheet-pill-h": "0.5rem",
        "sheet-pill-w": "25%",
        "sheet-pill-radius": "0.5rem",
        "drawer-resizer-h": "2.5rem",
        "drawer-resizer-w": "0.5rem",
        "resizer-radius": "0.5rem",
        "overlay-pt": "2.5rem",
        "overlay-p": "2.5rem",
    },
    dropdown: {
        radius: "0.5rem",
        p: "1rem",
        "header-mb": "0.5rem",
        "max-h": "24rem",
    },
    tooltip: {
        radius: "0.5rem",
        p: "0.75rem",
    },
    menu: {
        radius: "0.5rem",
        "item-p": "0.625rem",
        "max-h": "20rem",
    },
    stats: {
        radius: "1rem",
        p: "1.5rem",
        gap: "1rem",
        "icon-size": "2.5rem",
        "icon-p": "2rem",
        "inner-gap": "0.25rem",
        "footer-px": "1.5rem",
        "footer-py": "0.5rem",
    },
    notification: {
        radius: "0.75rem",
        p: "1rem",
        gap: "0.75rem",
        "inner-gap": "0.25rem",
        "close-p": "0.375rem",
        "close-radius": "0.5rem",
        "list-gap": "0.75rem",
        "badge-px": "0.75rem",
        "badge-py": "0.25rem",
    },
    command: {
        radius: "0.5rem",
        "item-p": "0.5rem",
        "item-gap": "0.5rem",
        "row-h": "2.5rem",
        "header-h": "3rem",
        "footer-h": "2rem",
        "footer-p": "0.5rem",
        "list-max-h": "24rem",
        "list-gap": "0.25rem",
        "list-my": "0.5rem",
        "group-px": "0.5rem",
        "group-pt": "0.5rem",
        "group-pb": "0.25rem",
        "icon-size": "2.5rem",
        "input-px": "0.5rem",
        "input-py": "0.5rem",
    },
    tag: {
        radius: "2rem",
        gap: "0.375rem",
        height: "2rem",
        "padding-x": "1rem",
        "padding-y": "0.5rem",
        "height-big": "3rem",
        "padding-x-big": "1.5rem",
        "padding-y-big": "1rem",
        "height-small": "1.5rem",
        "padding-x-small": "0.75rem",
        "padding-y-small": "0.5rem",
        "height-tiny": "1.25rem",
        "padding-x-tiny": "0.5rem",
        "padding-y-tiny": "0.25rem",
        "padding-icon": "0.25rem",
        "indicator-size": "0.5rem",
    },
    calendar: {
        "cell-p": "0.25rem",
        "day-size": "2.25rem",
        "nav-p": "0.375rem",
        "weekday-py": "0.5rem",
        "table-mt": "0.5rem",
        "datetime-my": "1rem",
        "footer-mt": "0.5rem",
        "header-radius": "0.25rem",
        "nav-gap": "0.125rem",
        "nav-py": "0.25rem",
        "year-w": "4rem",
        "icon-size": "1rem",
    },
    table: {
        radius: "0.5rem",
        "row-gap": "0.25rem",
        "row-pb": "1rem",
        "cell-px": "0.5rem",
        "loading-h": "3.5rem",
        "empty-h": "12rem",
        "groups-gap": "1rem",
        "metadata-mb": "0.25rem",
        "metadata-gap-x": "1rem",
        "metadata-gap-y": "0.25rem",
        "ops-py": "0.5rem",
        "ops-gap": "1rem",
        "filter-gap": "1rem",
        "pill-radius": "0.75rem",
        "pill-px": "1rem",
        "pill-py": "0.125rem",
        "pag-p": "0.75rem",
        "pag-gap": "1rem",
        "pag-items-gap": "0.5rem",
        "pag-item-px": "0.75rem",
        "pag-item-py": "0.25rem",
        "loading-bar-h": "0.5rem",
        "loading-bar-radius": "0.25rem",
        "filter-dot-size": "0.75rem",
        "filter-dot-mr": "0.5rem",
        "filter-row-gap": "0.75rem",
        "filter-inline-gap": "1rem",
        "filter-inline-py": "0.5rem",
        "filter-list-mt": "1rem",
    },
    skeleton: {
        radius: "0.25rem",
        height: "2rem",
        width: "8rem",
        "cell-h": "1.5rem",
        "list-gap": "1.5rem",
    },
    typography: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
    },
    input: {
        radius: "0.375rem",
        height: "2.5rem",
        "padding-x": "0.5rem",
        "padding-y": "0.25rem",
        gap: "0.5rem",
        text: "1rem",
        "label-text": "0.875rem",
        "hint-text": "0.75rem",
        "label-mb": "0.25rem",
        "hint-mt": "0.3rem",
        inline: "0.25rem",
        "slot-gap": "0.5rem",
        "slot-pl": "0.5rem",
        "slot-pr": "0.5rem",
    },
    checkbox: {
        size: "1rem",
        radius: "0.25rem",
        gap: "0.5rem",
        "hint-text": "0.75rem",
    },
    radiobox: {
        size: "1rem",
        gap: "0.5rem",
    },
    switch: {
        "track-h": "1.5rem",
        "track-w": "2.75rem",
        "thumb-size": "1.25rem",
        gap: "0.75rem",
        "label-text": "0.875rem",
        "hint-text": "0.75rem",
        "hint-mt": "0.25rem",
    },
    slider: {
        "control-h": "1.25rem",
        "track-h": "0.5rem",
        "thumb-size": "1.25rem",
    },
    "file-upload": {
        p: "1.5rem",
        radius: "0.5rem",
        gap: "1rem",
        "thumb-size": "4rem",
        "text-name": "1.125rem",
        "text-size": "0.875rem",
        "delete-py": "1rem",
        "inner-gap": "0.5rem",
        "thumb-my": "1rem",
        "thumb-gap": "0.25rem",
    },
    progress: {
        "track-h": "1.5rem",
    },
    spinner: {
        size: "3rem",
        border: "0.25rem",
        "container-p": "3rem",
    },
    empty: {
        gap: "1rem",
        px: "2rem",
        py: "3rem",
    },
    list: {
        radius: "1rem",
        "card-p": "1.5rem",
        "card-py": "1rem",
        "card-pb": "2rem",
        "card-gap": "1rem",
        "close-p": "0.25rem",
        "header-gap": "0.5rem",
        "item-py": "0.5rem",
        "item-gap": "1rem",
        "avatar-px": "0.25rem",
        "body-py": "0.25rem",
    },
    timeline: {
        "item-pb": "3rem",
        "connector-left": "1.5rem",
        "connector-top": "2rem",
        "connector-w": "0.125rem",
        "icon-size": "3rem",
        "icon-p": "0.5rem",
        "right-gap": "1.5rem",
        "right-px": "1rem",
    },
    step: {
        size: "2.5rem",
        "icon-size": "1.5rem",
        "label-px": "0.5rem",
        gap: "1rem",
    },
    tabs: {
        "header-mb": "0.5rem",
        "item-px": "2.5rem",
        "item-py": "1rem",
    },
    shortcut: {
        gap: "0.25rem",
        text: "0.875rem",
    },
    toolbar: {
        bottom: "1rem",
        radius: "0.5rem",
        p: "1rem",
    },
    wizard: {
        w: "20rem",
        gap: "0.75rem",
        radius: "0.5rem",
        p: "1rem",
        "footer-pt": "0.5rem",
        "actions-gap": "0.5rem",
        "counter-right": "0.5rem",
        "counter-top": "0.5rem",
        "label-text": "0.75rem",
    },
    info: {
        gap: "0.25rem",
        "label-text": "0.875rem",
        "value-text": "1rem",
        "secondary-text": "1.125rem",
    },
    "page-calendar": {
        gap: "1rem",
        "header-gap": "1rem",
        "date-gap": "0.75rem",
        "badge-size": "3rem",
        "badge-radius": "0.5rem",
        "title-text": "1.25rem",
        "week-label-text": "0.75rem",
        "nav-gap": "0.5rem",
        "nav-btn-gap": "0.25rem",
        "today-radius": "0.375rem",
        "today-px": "0.75rem",
        "today-py": "0.375rem",
        "today-text": "0.875rem",
        "view-switch-radius": "0.375rem",
        "filter-gap": "0.375rem",
        "filter-text": "0.75rem",
        "dot-size": "0.25rem",
        "dot-bottom": "0.125rem",
        "day-header-gap": "0.75rem",
        "day-header-px": "1rem",
        "day-header-py": "0.5rem",
        "day-badge-size": "2rem",
        "gutter-w": "60px",
        "side-px": "1rem",
        "detail-gap": "0.5rem",
        "detail-p": "0.75rem",
        "weekday-py": "0.5rem",
        "weekday-text": "0.75rem",
        "cell-min-h": "8rem",
        "cell-gap": "0.25rem",
        "cell-p": "0.5rem",
        "month-badge-size": "1.5rem",
        "month-badge-text": "0.75rem",
        "overflow-text": "1.125rem",
        "week-badge-size": "1.5rem",
        "week-badge-text": "0.875rem",
        "hour-text": "0.625rem",
        "pill-radius": "0.25rem",
        "pill-text": "0.75rem",
    },
};
