import type { ComponentTokens } from "./theme.types";

export const components: ComponentTokens = {
    card: {
        rounded: "1rem",
        "padding-x": "1.5rem",
        "padding-y": "0.75rem",
        gap: "1rem",
        "title-pb": "0.5rem",
        "title-mb": "0.5rem",
        "stats-icon-col-w": "5rem",
        "stats-icon-col-p": "1rem",
        "stats-icon-size": "3rem",
        "stats-content-gap": "0.5rem",
        "stats-content-py": "0.5rem",
        "title-text": "2.25rem",
    },
    button: {
        "height-big": "3rem",
        "height-min": "1.75rem",
        "height-small": "2rem",
        "height-tiny": "1.5rem",
        "padding-icon": "0.25rem",
        "padding-x": "1rem",
        "padding-x-big": "1.5rem",
        "padding-x-min": "0.75rem",
        "padding-x-small": "1rem",
        "padding-x-tiny": "0.5rem",
        "padding-y": "0.5rem",
        "padding-y-big": "1rem",
        "padding-y-min": "0.25rem",
        "padding-y-small": "0.5rem",
        "padding-y-tiny": "0.25rem",
        "radius-rough": "0.125rem",
        "radius-squared": "0px",
        "text-big": "1rem",
        "text-icon": "1rem",
        "text-min": "0.875rem",
        "text-small": "0.875rem",
        "text-tiny": "0.875rem",
        gap: "0.375rem",
        height: "2.5rem",
        rounded: "0.55rem",
        text: "1rem",
    },
    alert: {
        rounded: "0.5rem",
        p: "1rem",
        gap: "0.5rem",
        "close-top": "0.75rem",
        "close-right": "0.75rem",
    },
    modal: {
        "surface-min-inline-size": "20rem",
        "surface-gap": "1rem",
        "surface-radius": "0.5rem",
        "surface-padding-block": "1rem",
        "dialog-max-inline-size-mobile": "90%",
        "dialog-max-block-size": "40rem",
        "sheet-max-block-size": "calc(100vh - 15%)",
        "sheet-padding-block-start": "1.5rem",
        "sheet-padding-block-end": "1rem",
        "resizer-radius": "0.5rem",
        "focus-outline-offset": "0.125rem",
        "resizer-focus-ring-width": "0.25rem",
        "sheet-handle-inset-block-start": "0.25rem",
        "sheet-handle-block-size": "0.75rem",
        "sheet-handle-padding-block": "0.5rem",
        "drawer-resizer-inset-inline": "1.25rem",
        "drawer-resizer-inset-inline-start": "0.5rem",
        "drawer-resizer-block-size": "2.5rem",
        "drawer-resizer-inline-size": "0.5rem",
        "sheet-pill-block-size": "0.5rem",
        "sheet-pill-inline-size": "25%",
        "overlay-block-size": "100dvh",
        "overlay-padding-block-start": "2.5rem",
        "content-padding-inline": "2rem",
        "title-padding-block-end": "0.5rem",
        "title-font-size": "1.875rem",
        "title-line-height": "1.625",
        "body-padding-block": "0.25rem",
        "footer-padding-block-start": "1rem",
        "close-inset-inline-end": "1rem",
        "close-inset-block-start": "0.25rem",
        "close-button-padding": "0.25rem",
        "close-button-opacity": "0.7",
        "transition-duration": "375ms",
        "transition-timing": "cubic-bezier(0, 0, 0.58, 1)",
        "close-focus-ring-width": "0.125rem",
        "close-icon-size": "1.25rem",
        "confirm-dialog-max-inline-size": "24rem",
        "confirm-actions-gap": "0.5rem",
        "confirm-description-padding-block": "0.5rem",
        "overlay-background": "hsla(240, 6%, 10%, 0.8)",
    },
    dropdown: {
        "surface-radius": "0.5rem",
        "surface-padding": "1rem",
        "header-margin-block-end": "0.5rem",
        "title-font-size": "1.5rem",
        "title-letter-spacing": "0.025em",
        "list-max-block-size": "24rem",
        "surface-background": "hsla(0, 0%, 100%)",
        "surface-border": "hsla(240, 6%, 90%)",
        "surface-foreground": "hsla(240, 10%, 4%)",
    },
    expand: {} as ComponentTokens["expand"],
    tooltip: {
        "surface-radius": "0.5rem",
        "surface-padding": "0.75rem",
        "surface-background": "hsla(240, 10%, 4%)",
        "surface-border": "hsla(240, 10%, 4%)",
        "surface-foreground": "hsla(0, 0%, 100%)",
    },
    menu: {
        "surface-radius": "0.5rem",
        "surface-max-block-size": "20rem",
        "surface-background": "hsla(0, 0%, 100%)",
        "surface-border": "hsla(240, 6%, 90%)",
        "surface-foreground": "hsla(240, 10%, 4%)",
        "item-padding": "0.625rem",
        "item-min-inline-size": "9rem",
        "item-outline-width": "0.125rem",
        "item-outline-offset": "0.125rem",
        "item-expanded-opacity": "0.8",
        "item-disabled-opacity": "0.4",
        "item-active-background": "hsla(201, 49%, 36%)",
        "item-active-foreground": "hsla(221, 6%, 90%)",
        "nested-indicator-margin-inline-start": "0.625rem",
        "nested-indicator-font-size": "0.625rem",
        "nested-icon-size": "0.875rem",
        "item-icon-size": "1rem",
    },
    stats: {
        rounded: "1rem",
        p: "1.5rem",
        gap: "1rem",
        "icon-size": "2.5rem",
        "icon-p": "2rem",
        "inner-gap": "0.25rem",
        "title-text": "1rem",
        "value-text": "2.25rem",
        "footer-px": "1.5rem",
        "footer-py": "0.5rem",
    },
    notification: {
        rounded: "0.75rem",
        p: "1rem",
        gap: "0.75rem",
        "inner-gap": "0.25rem",
        "close-p": "0.375rem",
        "close-radius": "0.5rem",
        "list-gap": "0.75rem",
        "badge-px": "0.75rem",
        "badge-py": "0.25rem",
        "list-top": "1.5rem",
        "list-max-w": "380px",
        "badge-text": "0.625rem",
    },
    command: {
        rounded: "0.5rem",
        "item-p": "0.5rem",
        "item-gap": "0.5rem",
        "row-h": "2.5rem",
        "header-h": "3rem",
        "footer-h": "2rem",
        "footer-p": "0.5rem",
        "list-max-h": "24rem",
        "list-gap": "0.25rem",
        "list-my": "0.5rem",
        "group-px": "0.5rem",
        "group-pt": "0.5rem",
        "group-pb": "0.25rem",
        "icon-size": "2.5rem",
        "input-px": "0.5rem",
        "input-py": "0.5rem",
        "list-px": "0.5rem",
    },
    tag: {
        "surface-gap": "0.375rem",
        "surface-radius": "2rem",
        "default-min-block-size": "2rem",
        "default-padding-inline": "1rem",
        "default-padding-block": "0.5rem",
        "big-min-block-size": "3rem",
        "big-padding-inline": "1.5rem",
        "big-padding-block": "1rem",
        "small-min-block-size": "1.5rem",
        "small-padding-inline": "0.75rem",
        "small-padding-block": "0.5rem",
        "small-font-size": "0.875rem",
        "tiny-min-block-size": "1.25rem",
        "tiny-padding-inline": "0.5rem",
        "tiny-padding-block": "0.25rem",
        "tiny-font-size": "0.75rem",
        "icon-padding": "0.25rem",
        "indicator-size": "0.5rem",
    },

    calendar: {
        "cell-p": "0.25rem",
        "day-size": "2.25rem",
        "nav-p": "0.375rem",
        "weekday-py": "0.5rem",
        "table-mt": "0.5rem",
        "datetime-my": "1rem",
        "footer-mt": "0.5rem",
        "header-radius": "0.25rem",
        "nav-gap": "0.125rem",
        "nav-py": "0.25rem",
        "year-w": "4rem",
        "icon-size": "1rem",
        "weekday-text": "0.75rem",
        "cell-text": "0.75rem",
    },
    table: {
        rounded: "0.5rem",
        "groups-gap": "1rem",
        "inline-gap-tight": "0.25rem",
        "filter-gap": "1rem",
        "filter-row-gap": "0.75rem",
        "filter-inline-gap": "1rem",
        "filter-inline-padding-block": "0.5rem",
        "filter-list-margin-block-start": "1rem",
        "groups-margin-block-start": "1rem",
        "groups-margin-block": "1rem",
        "row-gap": "0.25rem",
        "row-padding-block-end": "1rem",
        "cell-padding": "0.75rem",
        "cell-padding-inline": "0.5rem",
        "cell-border": "1px",
        "head-cell-block-size": "3.5rem",
        "divider-width": "1px",
        "pagination-padding": "0.75rem",
        "pagination-gap": "1rem",
        "pagination-items-gap": "0.5rem",
        "pagination-item-padding-inline": "0.75rem",
        "pagination-item-padding-block": "0.25rem",
        "metadata-margin-block-end": "0.25rem",
        "metadata-gap-inline": "1rem",
        "metadata-gap-block": "0.25rem",
        "metadata-min-inline-size": "1ch",
        "operations-padding-block": "0.5rem",
        "operations-gap": "1rem",
        "pill-radius": "0.75rem",
        "pill-padding-inline": "1rem",
        "pill-padding-block": "0.125rem",
        "filter-dot-size": "0.75rem",
        "filter-dot-margin-inline-end": "0.5rem",
        "loading-block-size": "3.5rem",
        "loading-bar-block-size": "0.5rem",
        "loading-bar-radius": "0.25rem",
        "empty-block-size": "12rem",
    },

    skeleton: {
        rounded: "0.25rem",
        height: "2rem",
        width: "8rem",
        "cell-h": "1.5rem",
        "list-gap": "1.5rem",
    },
    typography: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
    },
    input: {
        rounded: "0.375rem",
        height: "2.5rem",
        "padding-x": "0.5rem",
        "padding-y": "0.25rem",
        gap: "0.5rem",
        text: "1rem",
        "label-text": "0.875rem",
        "hint-text": "0.75rem",
        "label-mb": "0.25rem",
        "hint-mt": "0.3rem",
        inline: "0.25rem",
        "slot-gap": "0.5rem",
        "slot-pl": "0.5rem",
        "slot-pr": "0.5rem",
    },
    checkbox: {
        size: "1rem",
        rounded: "0.25rem",
        gap: "0.5rem",
        "hint-text": "0.75rem",
    },
    radiobox: {
        size: "1rem",
        gap: "0.5rem",
    },
    switch: {
        "track-h": "1.5rem",
        "track-w": "2.75rem",
        "thumb-size": "1.25rem",
        gap: "0.75rem",
        "label-text": "0.875rem",
        "hint-text": "0.75rem",
        "hint-mt": "0.25rem",
    },
    slider: {
        "control-h": "1.25rem",
        "track-h": "0.5rem",
        "thumb-size": "1.25rem",
    },
    "file-upload": {
        p: "1.5rem",
        rounded: "0.5rem",
        gap: "1rem",
        "thumb-size": "4rem",
        "thumb-radius": "50%",
        "thumb-icon-size": "1.75rem",
        "text-name": "1.125rem",
        "text-size": "0.875rem",
        "delete-py": "1rem",
        "inner-gap": "0.5rem",
        "thumb-my": "1rem",
        "thumb-gap": "0.25rem",
    },
    progress: {
        "track-h": "1.5rem",
        rounded: "0.3rem",
    },
    spinner: {
        "indicator-size": "3rem",
        "indicator-border-width": "0.25rem",
        "container-padding": "3rem",
        "spin-duration": "1s",
    },
    empty: {
        gap: "1rem",
        px: "2rem",
        py: "3rem",
    },
    list: {
        rounded: "1rem",
        "card-p": "1.5rem",
        "card-py": "1rem",
        "card-pb": "2rem",
        "card-gap": "1rem",
        "close-p": "0.25rem",
        "header-gap": "0.5rem",
        "item-py": "0.5rem",
        "item-gap": "1rem",
        "avatar-px": "0.25rem",
        "body-py": "0.25rem",
        "title-text": "1.5rem",
    },
    timeline: {
        "item-padding-block-end": "3rem",
        "connector-inset-inline-start": "1.5rem",
        "connector-inset-block-start": "2rem",
        "connector-inline-size": "0.125rem",
        "content-gap": "0.75rem",
        "icon-size": "3rem",
        "icon-padding": "0.5rem",
        "actions-gap": "1.5rem",
        "actions-padding-inline": "1rem",
    },

    step: {
        size: "2.5rem",
        "icon-size": "1.5rem",
        "label-px": "0.5rem",
        gap: "1rem",
        "connector-h": "2px",
    },
    tabs: {
        "header-margin-block-end": "0.5rem",
        "tab-padding-inline": "2.5rem",
        "tab-padding-block": "1rem",
        "divider-block-size": "1px",
        "active-divider-block-size": "2px",
        "item-transition-duration": "375ms",
    },

    shortcut: {
        gap: "0.25rem",
        text: "0.875rem",
    },
    toolbar: {
        bottom: "1rem",
        rounded: "0.5rem",
        p: "1rem",
    },
    wizard: {
        w: "20rem",
        gap: "0.75rem",
        rounded: "0.5rem",
        p: "1rem",
        "footer-pt": "0.5rem",
        "actions-gap": "0.5rem",
        "counter-right": "0.5rem",
        "counter-top": "0.5rem",
        "label-text": "0.75rem",
    },
    info: {
        gap: "0.25rem",
        "label-text": "0.875rem",
        "value-text": "1rem",
        "secondary-text": "1.125rem",
    },
    "page-calendar": {
        gap: "1rem",
        "header-gap": "1rem",
        "date-gap": "0.75rem",
        "badge-size": "3rem",
        "badge-radius": "0.5rem",
        "title-text": "1.25rem",
        "week-label-text": "0.75rem",
        "nav-gap": "0.5rem",
        "nav-button-gap": "0.25rem",
        "today-radius": "0.375rem",
        "today-padding-inline": "0.75rem",
        "today-padding-block": "0.375rem",
        "today-font-size": "0.875rem",
        "view-switch-radius": "0.375rem",
        "filter-gap": "0.375rem",
        "filter-font-size": "0.75rem",
        "dot-size": "0.25rem",
        "dot-bottom": "0.125rem",
        "day-header-gap": "0.75rem",
        "day-header-padding-inline": "1rem",
        "day-header-padding-block": "0.5rem",
        "day-badge-size": "2rem",
        "gutter-width": "60px",
        "side-padding-inline": "1rem",
        "detail-gap": "0.5rem",
        "detail-padding": "0.75rem",
        "weekday-padding-block": "0.5rem",
        "weekday-font-size": "0.75rem",
        "cell-min-block-size": "8rem",
        "cell-gap": "0.25rem",
        "cell-padding": "0.5rem",
        "month-badge-size": "1.5rem",
        "month-badge-font-size": "0.75rem",
        "overflow-font-size": "1.125rem",
        "week-badge-size": "1.5rem",
        "week-badge-font-size": "0.875rem",
        "hour-font-size": "0.625rem",
        "pill-radius": "0.25rem",
        "pill-font-size": "0.75rem",
        "cell-gap-tight": "0.125rem",
        "filter-label-margin-inline-end": "0.25rem",
    },
};
