/** Library geometry defaults. Inspect these values rather than computed custom properties.
 * Defaults are CSS fallbacks so nested spacing/radius scopes remain reactive.
 * Explicit semantic overrides are inherited normally and always take precedence.
 */
export const defaultGeometryBases = { spacing: "1rem", radius: "1rem" } as const;

export const defaultGeometryTokens = {
    "--var-button-icon-font-size": "calc(var(--var-spacing-base) * 1)",
    "--var-page-calendar-hour-block-size": "calc(var(--var-spacing-base) * 3)",
    "--var-spacing": "calc(var(--var-spacing-base) * 0.75)",
    "--var-typography-description-margin-block-end": "calc( var(--var-spacing-base) * 1 )",
    "--var-typography-info-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-typography-page-header-gap": "calc(var(--var-spacing-base) * 1.5)",
    "--var-typography-page-header-actions-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-spacing-hairline": "calc(var(--var-spacing-base) * 0.0625)",
    "--var-spacing-lg": "calc(var(--var-spacing-base) * 1.125)",
    "--var-spacing-sm": "calc(var(--var-spacing-base) * 0.75)",
    "--var-spacing-dialog": "calc(var(--var-spacing-base) * 20)",
    "--var-rounded-pill": "calc(var(--var-radius-base) * 2)",
    "--var-card-content-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-card-surface-radius": "calc( var(--var-radius, 0px) + calc(var(--var-radius-base) / 4) )",
    "--var-card-surface-padding-block": "calc(var(--var-spacing-base) * 0.75)",
    "--var-card-content-padding-inline": "calc(var(--var-spacing-base) * 1.5)",
    "--var-card-title-margin-block-end": "calc(var(--var-spacing-base) / 2)",
    "--var-card-title-padding-block-end": "calc(var(--var-spacing-base) / 2)",
    "--var-card-header-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-card-actions-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-card-stats-icon-column-width": "calc(var(--var-spacing-base) * 5)",
    "--var-card-stats-icon-column-padding": "calc(var(--var-spacing-base) * 1)",
    "--var-card-stats-icon-size": "calc(var(--var-spacing-base) * 3)",
    "--var-card-stats-content-gap": "calc(var(--var-spacing-base) / 2)",
    "--var-card-stats-content-padding-block": "calc(var(--var-spacing-base) / 2)",
    "--var-card-stats-loading-block-size": "calc(var(--var-spacing-base) * 2.5)",
    "--var-alert-icon-size": "calc(var(--var-spacing-base) * 1.25)",
    "--var-alert-surface-radius": "calc( var(--var-radius, calc(var(--var-radius-base) / 2)) - calc(var(--var-radius-base) / 4) )",
    "--var-alert-surface-padding": "calc(var(--var-spacing-base) * 1)",
    "--var-alert-content-gap": "calc(var(--var-spacing-base) / 2)",
    "--var-alert-close-inset-block-start": "calc(var(--var-spacing-base) * 0.75)",
    "--var-alert-close-inset-inline-end": "calc(var(--var-spacing-base) * 0.75)",
    "--var-swipeable-list-root-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-swipeable-list-content-gap": "calc(var(--var-spacing-base) * 0.75)",
    "--var-swipeable-list-surface-radius": "calc( var(--var-radius, 0px) + var(--var-radius-base) )",
    "--var-swipeable-list-surface-min-block-size": "calc( var(--var-spacing-base) * 4.5 )",
    "--var-swipeable-list-surface-padding-inline": "calc(var(--var-spacing-base) * 1)",
    "--var-swipeable-list-surface-padding-block": "calc(var(--var-spacing-base) * 0.75)",
    "--var-swipeable-list-action-icon-size": "calc(var(--var-spacing-base) * 2.25)",
    "--var-swipeable-list-action-focus-ring-width": "calc( var(--var-spacing-base) * 0.125 )",
    "--var-swipeable-list-action-focus-ring-offset": "calc( var(--var-spacing-base) * 0.125 )",
    "--var-swipeable-list-description-margin-block-start": "calc( var(--var-spacing-base) * 0.125 )",
    "--var-button-height": "calc(var(--var-spacing-base) * 2.5)",
    "--var-button-px": "calc(var(--var-spacing-base) * 1)",
    "--var-button-py": "calc(var(--var-spacing-base) / 2)",
    "--var-button-gap": "calc(var(--var-spacing-base) * 0.375)",
    "--var-button-rounded": "calc(var(--var-radius, var(--var-radius-base)) * 0.733333)",
    "--var-button-big-height": "calc(var(--var-spacing-base) * 3)",
    "--var-button-big-px": "calc(var(--var-spacing-base) * 1.5)",
    "--var-button-big-py": "calc(var(--var-spacing-base) * 1)",
    "--var-button-min-height": "calc(var(--var-spacing-base) * 1.75)",
    "--var-button-min-px": "calc(var(--var-spacing-base) * 0.75)",
    "--var-button-min-py": "calc(var(--var-spacing-base) / 4)",
    "--var-button-small-height": "calc(var(--var-spacing-base) * 2)",
    "--var-button-small-px": "calc(var(--var-spacing-base) * 1)",
    "--var-button-small-py": "calc(var(--var-spacing-base) / 2)",
    "--var-button-tiny-height": "calc(var(--var-spacing-base) * 1.5)",
    "--var-button-tiny-px": "calc(var(--var-spacing-base) / 2)",
    "--var-button-tiny-py": "calc(var(--var-spacing-base) / 4)",
    "--var-button-icon-p": "calc(var(--var-spacing-base) / 4)",
    "--var-button-rough-rounded": "calc(var(--var-radius, var(--var-radius-base)) / 6)",
    "--var-button-focus-ring-width": "calc(var(--var-spacing-base) / 4)",
    "--var-calendar-day-cell-padding": "calc(var(--var-spacing-base) / 4)",
    "--var-calendar-day-button-size": "calc(var(--var-spacing-base) * 2.25)",
    "--var-calendar-focus-ring-width": "calc(var(--var-spacing-base) / 4)",
    "--var-calendar-selected-ring-width": "calc(var(--var-spacing-base) / 4)",
    "--var-calendar-header-radius": "calc(var(--var-radius, var(--var-radius-base)) * 0.733333)",
    "--var-calendar-table-margin-block-start": "calc(var(--var-spacing-base) * 1)",
    "--var-calendar-nav-button-padding": "calc(var(--var-spacing-base) / 4)",
    "--var-calendar-nav-icon-size": "calc(var(--var-spacing-base) * 1)",
    "--var-calendar-month-controls-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-calendar-month-controls-padding-block": "calc( var(--var-spacing-base) / 4 )",
    "--var-calendar-year-input-width": "calc(var(--var-spacing-base) * 4)",
    "--var-calendar-weekday-padding-block": "calc(var(--var-spacing-base) * 0.5)",
    "--var-calendar-datetime-margin-block": "calc(var(--var-spacing-base) * 1)",
    "--var-calendar-footer-margin-block-start": "calc(var(--var-spacing-base) * 1)",
    "--var-calendar-range-label-inset-block-start": "calc( var(--var-spacing-base) * -0.5 )",
    "--var-input-field-icon-size": "calc(var(--var-spacing-base) * 1)",
    "--var-input-field-small-icon-size": "calc(var(--var-spacing-base) * 0.875)",
    "--var-input-field-label-row-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-input-field-label-meta-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-input-field-tooltip-icon-size": "calc(var(--var-spacing-base) * 0.75)",
    "--var-input-field-small-tooltip-icon-size": "calc(var(--var-spacing-base) * 0.6875)",
    "--var-input-field-tooltip-max-inline-size": "calc(var(--var-spacing-base) * 12)",
    "--var-input-field-status-min-inline-size": "calc(var(--var-spacing-base) * 1.5)",
    "--var-input-field-small-status-min-inline-size": "calc( var(--var-spacing-base) * 1.25 )",
    "--var-input-field-status-block-size": "calc(var(--var-spacing-base) * 0.75)",
    "--var-input-field-small-status-block-size": "calc( var(--var-spacing-base) * 0.625 )",
    "--var-input-field-status-indicator-size": "calc(var(--var-spacing-base) * 0.75)",
    "--var-input-field-small-status-indicator-size": "calc( var(--var-spacing-base) * 0.625 )",
    "--var-input-field-label-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-input-field-control-column-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-input-field-small-control-column-gap": "calc( var(--var-spacing-base) * 0.375 )",
    "--var-input-field-control-row-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-input-field-small-control-row-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-input-field-control-radius": "calc(var(--var-radius, var(--var-radius-base)) * 0.375)",
    "--var-input-field-slot-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-input-field-small-slot-gap": "calc(var(--var-spacing-base) * 0.375)",
    "--var-input-field-slot-padding-inline-start": "calc( var(--var-spacing-base) * 0.5 )",
    "--var-input-field-small-slot-padding-inline-start": "calc( var(--var-spacing-base) * 0.375 )",
    "--var-input-field-slot-padding-inline-end": "calc( var(--var-spacing-base) * 0.5 )",
    "--var-input-field-small-slot-padding-inline-end": "calc( var(--var-spacing-base) * 0.375 )",
    "--var-input-field-hint-margin-block-start": "calc( var(--var-spacing-base) * 0.3 )",
    "--var-free-text-control-height": "calc(var(--var-spacing-base) * 2.5)",
    "--var-free-text-big-control-height": "calc(var(--var-spacing-base) * 3)",
    "--var-free-text-min-control-height": "calc(var(--var-spacing-base) * 1.75)",
    "--var-free-text-small-control-height": "calc(var(--var-spacing-base) * 2)",
    "--var-free-text-tiny-control-height": "calc(var(--var-spacing-base) * 1.5)",
    "--var-free-text-surface-radius": "calc(var(--var-radius, var(--var-radius-base)) * 0.375)",
    "--var-free-text-surface-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
    "--var-free-text-big-surface-padding-inline": "calc(var(--var-spacing-base) * 1.5)",
    "--var-free-text-min-surface-padding-inline": "calc(var(--var-spacing-base) * 0.75)",
    "--var-free-text-small-surface-padding-inline": "calc( var(--var-spacing-base) * 0.375 )",
    "--var-free-text-tiny-surface-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
    "--var-free-text-surface-padding-block": "calc(var(--var-spacing-base) * 0.25)",
    "--var-free-text-small-surface-padding-block": "calc( var(--var-spacing-base) * 0.125 )",
    "--var-free-text-outline-width": "calc(var(--var-spacing-base) * 0.125)",
    "--var-free-text-outline-offset": "calc(var(--var-spacing-base) * 0.125)",
    "--var-dropdown-surface-radius": "calc( var(--var-radius, 0px) + calc(var(--var-radius-base) / 2) )",
    "--var-dropdown-surface-padding": "calc(var(--var-spacing-base) * 1)",
    "--var-dropdown-header-margin-block-end": "calc(var(--var-spacing-base) / 2)",
    "--var-dropdown-list-max-block-size": "calc(var(--var-spacing-base) * 24)",
    "--var-menu-surface-radius": "calc( var(--var-radius, 0px) + calc(var(--var-radius-base) / 2) )",
    "--var-menu-surface-max-block-size": "calc(var(--var-spacing-base) * 20)",
    "--var-menu-item-padding": "calc(var(--var-spacing-base) * 0.625)",
    "--var-menu-item-min-inline-size": "calc(var(--var-spacing-base) * 9)",
    "--var-menu-item-outline-width": "calc(var(--var-spacing-base) * 0.125)",
    "--var-menu-item-outline-offset": "calc(var(--var-spacing-base) * 0.125)",
    "--var-autocomplete-list-max-block-size": "calc(var(--var-spacing-base) * 24)",
    "--var-autocomplete-panel-radius": "calc( var(--var-radius, 0px) + calc(var(--var-radius-base) / 2) )",
    "--var-autocomplete-option-min-block-size": "calc(var(--var-spacing-base) * 2.5)",
    "--var-autocomplete-option-padding": "calc(var(--var-spacing-base) * 0.625)",
    "--var-autocomplete-actions-gap": "calc(var(--var-spacing-base) * 0.125)",
    "--var-autocomplete-action-padding": "calc(var(--var-spacing-base) * 0.5)",
    "--var-autocomplete-action-padding-md": "calc(var(--var-spacing-base) * 0.25)",
    "--var-autocomplete-panel-max-block-size": "calc(var(--var-spacing-base) * 20)",
    "--var-multi-select-field-min-inline-size": "calc(var(--var-spacing-base) * 12)",
    "--var-multi-select-tag-remove-icon-size": "calc(var(--var-spacing-base) * 0.875)",
    "--var-multi-select-tags-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-multi-select-actions-gap": "calc(var(--var-spacing-base) * 0.125)",
    "--var-multi-select-search-margin-block-end": "calc( var(--var-spacing-base) * 0.25 )",
    "--var-multi-select-option-padding": "calc(var(--var-spacing-base) * 0.625)",
    "--var-multi-select-results-max-block-size": "calc(var(--var-spacing-base) * 18)",
    "--var-multi-select-checkbox-margin-inline-end": "calc( var(--var-spacing-base) * 0.5 )",
    "--var-multi-select-footer-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-radiobox-label-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-radiobox-label-min-block-size": "calc(var(--var-spacing-base) * 1.25)",
    "--var-radiobox-control-size": "calc(var(--var-spacing-base) * 1)",
    "--var-radiobox-large-control-size": "calc(var(--var-spacing-base) * 1.25)",
    "--var-radiobox-control-border-width": "calc(var(--var-spacing-base) * 0.0625)",
    "--var-radiobox-mark-size": "calc(var(--var-spacing-base) * 0.375)",
    "--var-radiobox-large-mark-size": "calc(var(--var-spacing-base) * 0.46875)",
    "--var-radiobox-focus-ring-width": "calc(var(--var-spacing-base) * 0.125)",
    "--var-radiobox-focus-ring-offset": "calc(var(--var-spacing-base) * 0.125)",
    "--var-checkbox-label-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-checkbox-control-size": "calc(var(--var-spacing-base) * 1)",
    "--var-checkbox-control-radius": "calc(var(--var-radius, var(--var-radius-base)) * 0.25)",
    "--var-checkbox-control-border-width": "calc(var(--var-spacing-base) * 0.0625)",
    "--var-checkbox-mark-stroke-width": "calc(var(--var-spacing-base) * 0.125)",
    "--var-checkbox-mark-inline-size": "calc(var(--var-spacing-base) * 0.35)",
    "--var-checkbox-mark-block-size": "calc(var(--var-spacing-base) * 0.6)",
    "--var-checkbox-indeterminate-mark-inline-size": "calc( var(--var-spacing-base) * 0.55 )",
    "--var-checkbox-focus-ring-width": "calc(var(--var-spacing-base) * 0.125)",
    "--var-checkbox-focus-ring-offset": "calc(var(--var-spacing-base) * 0.125)",
    "--var-switch-track-block-size": "calc(var(--var-spacing-base) * 1.25)",
    "--var-switch-track-inline-size": "calc(var(--var-spacing-base) * 2.25)",
    "--var-switch-track-focus-ring-width": "calc(var(--var-spacing-base) * 0.125)",
    "--var-switch-track-focus-ring-offset": "calc(var(--var-spacing-base) * 0.125)",
    "--var-switch-thumb-size": "calc(var(--var-spacing-base) * 1)",
    "--var-switch-thumb-checked-translate-inline": "calc( var(--var-spacing-base) * 1.25 )",
    "--var-switch-label-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-switch-error-margin-block-start": "calc(var(--var-spacing-base) * 0.25)",
    "--var-date-picker-calendar-icon-size": "calc(var(--var-spacing-base) * 1)",
    "--var-date-picker-panel-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-date-picker-panel-padding": "calc(var(--var-spacing-base) * 1)",
    "--var-date-picker-range-nights-radius": "var(--var-card-surface-radius, calc(var(--var-radius, 0px) + calc(var(--var-radius-base) / 4)))",
    "--var-date-picker-presets-inline-size": "calc(var(--var-spacing-base) * 13)",
    "--var-date-picker-preset-padding-block": "calc(var(--var-spacing-base) * 0.625)",
    "--var-date-picker-preset-padding-inline": "calc( var(--var-spacing-base) * 0.875 )",
    "--var-date-picker-action-button-padding-block": "calc( var(--var-spacing-base) * 0.625 )",
    "--var-date-picker-action-button-padding-inline": "calc( var(--var-spacing-base) * 1 )",
    "--var-slider-control-block-size": "calc(var(--var-spacing-base) * 1.25)",
    "--var-slider-track-block-size": "calc(var(--var-spacing-base) * 0.5)",
    "--var-slider-thumb-size": "calc(var(--var-spacing-base) * 1.25)",
    "--var-slider-thumb-focus-outline-width": "calc(var(--var-spacing-base) * 0.125)",
    "--var-slider-thumb-focus-outline-offset": "calc( var(--var-spacing-base) * 0.125 )",
    "--var-file-upload-surface-padding": "calc(var(--var-spacing-base) * 1.5)",
    "--var-file-upload-surface-radius": "calc(var(--var-radius-base) * 0.5)",
    "--var-file-upload-content-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-file-upload-thumb-size": "calc(var(--var-spacing-base) * 4)",
    "--var-file-upload-thumb-icon-size": "calc(var(--var-spacing-base) * 1.75)",
    "--var-file-upload-file-icon-size": "calc(var(--var-spacing-base) * 3)",
    "--var-file-upload-remove-icon-size": "calc(var(--var-spacing-base) * 1)",
    "--var-file-upload-idle-icon-size": "calc(var(--var-spacing-base) * 5)",
    "--var-file-upload-preview-button-margin": "calc(var(--var-spacing-base) * 0.5)",
    "--var-file-upload-item-border-width": "calc(var(--var-spacing-base) * 0.0625)",
    "--var-file-upload-actions-padding-block": "calc(var(--var-spacing-base) * 1)",
    "--var-file-upload-remove-button-size": "calc(var(--var-spacing-base) * 1.5)",
    "--var-file-upload-list-gap": "calc(var(--var-spacing-base) * 2)",
    "--var-file-upload-idle-icon-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-file-upload-idle-copy-margin-block": "calc(var(--var-spacing-base) * 1)",
    "--var-file-upload-idle-copy-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-file-upload-viewer-media-max-inline-size": "calc( var(--var-spacing-base) * 24 )",
    "--var-menu-nested-indicator-margin-inline-start": "calc( var(--var-spacing-base) * 0.625 )",
    "--var-menu-nested-icon-size": "calc(var(--var-spacing-base) * 0.875)",
    "--var-menu-item-icon-size": "calc(var(--var-spacing-base) * 1)",
    "--var-command-dialog-max-inline-size-md": "calc(var(--var-spacing-base) * 40)",
    "--var-command-dialog-max-inline-size-lg": "calc(var(--var-spacing-base) * 48)",
    "--var-command-row-block-size": "calc(var(--var-spacing-base) * 2.5)",
    "--var-command-header-block-size": "calc(var(--var-spacing-base) * 3)",
    "--var-command-footer-block-size": "calc(var(--var-spacing-base) * 2)",
    "--var-command-footer-padding": "calc(var(--var-spacing-base) * 0.5)",
    "--var-command-list-max-block-size": "calc(var(--var-spacing-base) * 24)",
    "--var-command-list-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-command-list-margin-block": "calc(var(--var-spacing-base) * 0.5)",
    "--var-command-list-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
    "--var-command-group-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
    "--var-command-group-padding-block-start": "calc(var(--var-spacing-base) * 0.5)",
    "--var-command-group-padding-block-end": "calc(var(--var-spacing-base) * 0.25)",
    "--var-command-item-radius": "calc( var(--var-radius, 0px) + calc(var(--var-radius-base) / 2) )",
    "--var-command-item-padding": "calc(var(--var-spacing-base) * 0.5)",
    "--var-command-item-content-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-command-search-icon-frame-size": "calc(var(--var-spacing-base) * 2.5)",
    "--var-command-search-icon-size": "calc(var(--var-spacing-base) * 1)",
    "--var-command-input-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
    "--var-command-input-padding-block": "calc(var(--var-spacing-base) * 0.5)",
    "--var-command-input-outline-width": "calc(var(--var-spacing-base) * 0.125)",
    "--var-command-input-outline-offset": "calc(var(--var-spacing-base) * 0.125)",
    "--var-tooltip-surface-radius": "calc( var(--var-radius, 0px) + calc(var(--var-radius-base) / 2) )",
    "--var-tooltip-surface-padding": "calc(var(--var-spacing-base) * 0.75)",
    "--var-tag-surface-gap": "calc(var(--var-spacing-base) * 0.375)",
    "--var-tag-surface-radius": "calc(var(--var-radius, var(--var-radius-base)) * 2.666667)",
    "--var-tag-default-min-block-size": "calc(var(--var-spacing-base) * 2)",
    "--var-tag-default-padding-inline": "calc(var(--var-spacing-base) * 1)",
    "--var-tag-default-padding-block": "calc(var(--var-spacing-base) * 0.5)",
    "--var-tag-big-min-block-size": "calc(var(--var-spacing-base) * 3)",
    "--var-tag-big-padding-inline": "calc(var(--var-spacing-base) * 1.5)",
    "--var-tag-big-padding-block": "calc(var(--var-spacing-base) * 1)",
    "--var-tag-small-min-block-size": "calc(var(--var-spacing-base) * 1.5)",
    "--var-tag-small-padding-inline": "calc(var(--var-spacing-base) * 0.75)",
    "--var-tag-small-padding-block": "calc(var(--var-spacing-base) * 0.5)",
    "--var-tag-tiny-min-block-size": "calc(var(--var-spacing-base) * 1.25)",
    "--var-tag-tiny-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
    "--var-tag-tiny-padding-block": "calc(var(--var-spacing-base) * 0.25)",
    "--var-tag-icon-padding": "calc(var(--var-spacing-base) * 0.25)",
    "--var-tag-indicator-size": "calc(var(--var-spacing-base) * 0.5)",
    "--var-spinner-indicator-size": "calc(var(--var-spacing-base) * 3)",
    "--var-spinner-indicator-border-width": "calc(var(--var-spacing-base) * 0.25)",
    "--var-spinner-container-padding": "calc(var(--var-spacing-base) * 3)",
    "--var-empty-surface-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-empty-surface-padding-inline": "calc(var(--var-spacing-base) * 2)",
    "--var-empty-surface-padding-block": "calc(var(--var-spacing-base) * 3)",
    "--var-empty-icon-size": "calc(var(--var-spacing-base) * 4)",
    "--var-list-detail-card-min-inline-size": "calc(var(--var-spacing-base) * 20)",
    "--var-list-detail-card-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-list-detail-card-radius": "calc(var(--var-radius, var(--var-radius-base)) * 1.333333)",
    "--var-list-detail-card-padding": "calc(var(--var-spacing-base) * 1.5)",
    "--var-list-detail-card-padding-block": "calc(var(--var-spacing-base) * 1.5)",
    "--var-list-detail-card-padding-block-end": "calc(var(--var-spacing-base) * 1.5)",
    "--var-list-close-inset-inline-end": "calc(var(--var-spacing-base) * 1)",
    "--var-list-close-inset-block-start": "calc(var(--var-spacing-base) / 4)",
    "--var-list-close-button-padding": "calc(var(--var-spacing-base) * 0.5)",
    "--var-list-header-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-list-item-padding-block": "calc(var(--var-spacing-base) * 1)",
    "--var-list-item-media-gap": "calc(var(--var-spacing-base) * 0.75)",
    "--var-list-avatar-frame-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
    "--var-list-avatar-button-size": "calc(var(--var-spacing-base) * 2.5)",
    "--var-list-item-body-padding-block": "calc(var(--var-spacing-base) * 0.5)",
    "--var-list-item-content-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-modal-surface-min-inline-size": "calc(var(--var-spacing-base) * 20)",
    "--var-modal-surface-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-modal-dialog-max-inline-size-mobile": "calc(var(--var-spacing-base) * 20)",
    "--var-modal-dialog-max-block-size": "calc(var(--var-spacing-base) * 40)",
    "--var-modal-surface-radius": "calc(var(--var-radius, var(--var-radius-base)) * 1.333333)",
    "--var-modal-surface-padding-block": "calc(var(--var-spacing-base) * 1.5)",
    "--var-modal-sheet-padding-block-start": "calc(var(--var-spacing-base) * 1.5)",
    "--var-modal-sheet-padding-block-end": "calc(var(--var-spacing-base) * 1.5)",
    "--var-modal-resizer-radius": "calc(var(--var-radius, var(--var-radius-base)) * 0.666667)",
    "--var-modal-focus-outline-offset": "calc(var(--var-spacing-base) * 0.125)",
    "--var-modal-resizer-focus-ring-width": "calc(var(--var-spacing-base) / 4)",
    "--var-modal-sheet-handle-inset-block-start": "calc(var(--var-spacing-base) / 4)",
    "--var-modal-sheet-handle-block-size": "calc(var(--var-spacing-base) * 1)",
    "--var-modal-sheet-handle-padding-block": "calc(var(--var-spacing-base) / 4)",
    "--var-modal-drawer-resizer-inset-inline": "calc(var(--var-spacing-base) * 1.25)",
    "--var-modal-drawer-resizer-inset-inline-start": "calc( var(--var-spacing-base) * 0.5 )",
    "--var-modal-drawer-resizer-block-size": "calc(var(--var-spacing-base) * 4)",
    "--var-modal-drawer-resizer-inline-size": "calc(var(--var-spacing-base) * 0.5)",
    "--var-modal-sheet-pill-block-size": "calc(var(--var-spacing-base) * 0.25)",
    "--var-modal-sheet-pill-inline-size": "calc(var(--var-spacing-base) * 4)",
    "--var-modal-overlay-padding-block-start": "calc(var(--var-spacing-base) * 1.5)",
    "--var-modal-content-padding-inline": "calc(var(--var-spacing-base) * 1.5)",
    "--var-modal-title-padding-block-end": "calc(var(--var-spacing-base) * 1)",
    "--var-modal-body-padding-block": "calc(var(--var-spacing-base) * 1)",
    "--var-modal-footer-padding-block-start": "calc(var(--var-spacing-base) * 1)",
    "--var-modal-close-inset-inline-end": "calc(var(--var-spacing-base) * 1)",
    "--var-modal-close-inset-block-start": "calc(var(--var-spacing-base) * 1)",
    "--var-modal-close-button-padding": "calc(var(--var-spacing-base) * 0.5)",
    "--var-modal-close-focus-ring-width": "calc(var(--var-spacing-base) * 0.125)",
    "--var-modal-close-icon-size": "calc(var(--var-spacing-base) * 1.25)",
    "--var-modal-confirm-dialog-max-inline-size": "calc( var(--var-spacing-base) * 24 )",
    "--var-modal-confirm-actions-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-modal-confirm-description-padding-block": "calc( var(--var-spacing-base) * 1 )",
    "--var-notification-surface-radius": "calc(var(--var-radius, var(--var-radius-base)) * 1.333333)",
    "--var-notification-surface-backdrop-blur": "calc( var(--var-spacing-base) * 0.75 )",
    "--var-notification-content-gap": "calc(var(--var-spacing-base) * 0.75)",
    "--var-notification-content-padding": "calc(var(--var-spacing-base) * 1)",
    "--var-notification-icon-margin-block-start": "calc( var(--var-spacing-base) * 0.125 )",
    "--var-notification-icon-size": "calc(var(--var-spacing-base) * 1)",
    "--var-notification-text-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-notification-close-margin-block-start": "calc( var(--var-spacing-base) * -0.25 )",
    "--var-notification-close-margin-inline-end": "calc( var(--var-spacing-base) * -0.25 )",
    "--var-notification-close-radius": "calc(var(--var-radius, var(--var-radius-base)) * 0.666667)",
    "--var-notification-close-padding": "calc(var(--var-spacing-base) * 0.25)",
    "--var-notification-close-icon-size": "calc(var(--var-spacing-base) * 0.875)",
    "--var-notification-viewport-inset-block-start": "calc( var(--var-spacing-base) * 1 )",
    "--var-notification-viewport-max-inline-size": "calc( var(--var-spacing-base) * 28 )",
    "--var-notification-viewport-gap": "calc(var(--var-spacing-base) * 0.75)",
    "--var-notification-viewport-outline-offset": "calc( var(--var-spacing-base) * 0.125 )",
    "--var-notification-badge-padding-inline": "calc(var(--var-spacing-base) * 0.75)",
    "--var-notification-badge-padding-block": "calc(var(--var-spacing-base) * 0.25)",
    "--var-notification-badge-backdrop-blur": "calc(var(--var-spacing-base) * 0.5)",
    "--var-progress-track-block-size": "calc(var(--var-spacing-base) * 1.5)",
    "--var-progress-track-radius": "calc(var(--var-radius, var(--var-radius-base)) * 0.4)",
    "--var-tabs-header-margin-block-end": "calc(var(--var-spacing-base) * 0.5)",
    "--var-tabs-tab-padding-inline": "calc(var(--var-spacing-base) * 2.5)",
    "--var-tabs-tab-padding-block": "calc(var(--var-spacing-base) * 1)",
    "--var-timeline-item-padding-block-end": "calc(var(--var-spacing-base) * 2)",
    "--var-timeline-connector-inset-inline-start": "calc(var(--var-spacing-base) * 1)",
    "--var-timeline-connector-inset-block-start": "calc(var(--var-spacing-base) * 2)",
    "--var-timeline-content-gap": "calc(var(--var-spacing-base) * 0.75)",
    "--var-timeline-icon-size": "calc(var(--var-spacing-base) * 2)",
    "--var-timeline-icon-padding": "calc(var(--var-spacing-base) * 0.5)",
    "--var-timeline-actions-gap": "calc(var(--var-spacing-base) * 1.5)",
    "--var-timeline-actions-padding-inline": "calc(var(--var-spacing-base) * 1)",
    "--var-step-marker-size": "calc(var(--var-spacing-base) * 2.5)",
    "--var-step-icon-size": "calc(var(--var-spacing-base) * 1.5)",
    "--var-step-label-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
    "--var-step-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-page-calendar-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-page-calendar-header-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-page-calendar-header-nav-icon-size": "calc(var(--var-spacing-base) * 1)",
    "--var-page-calendar-header-icon-size": "calc(var(--var-spacing-base) * 0.875)",
    "--var-page-calendar-date-gap": "calc(var(--var-spacing-base) * 0.75)",
    "--var-page-calendar-badge-size": "calc(var(--var-spacing-base) * 3)",
    "--var-page-calendar-badge-radius": "calc(var(--var-radius, var(--var-radius-base)) * 0.666667)",
    "--var-page-calendar-nav-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-page-calendar-nav-button-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-page-calendar-today-radius": "calc(var(--var-radius, var(--var-radius-base)) * 0.5)",
    "--var-page-calendar-today-padding-inline": "calc( var(--var-spacing-base) * 0.75 )",
    "--var-page-calendar-today-padding-block": "calc( var(--var-spacing-base) * 0.375 )",
    "--var-page-calendar-view-switch-radius": "calc(var(--var-radius, var(--var-radius-base)) * 0.5)",
    "--var-page-calendar-filter-gap": "calc(var(--var-spacing-base) * 0.375)",
    "--var-page-calendar-filter-label-margin-inline-end": "calc( var(--var-spacing-base) * 0.25 )",
    "--var-page-calendar-dot-size": "calc(var(--var-spacing-base) * 0.25)",
    "--var-page-calendar-dot-bottom": "calc(var(--var-spacing-base) * 0.125)",
    "--var-page-calendar-day-header-gap": "calc(var(--var-spacing-base) * 0.75)",
    "--var-page-calendar-day-header-padding-inline": "calc( var(--var-spacing-base) * 1 )",
    "--var-page-calendar-day-header-padding-block": "calc( var(--var-spacing-base) * 0.5 )",
    "--var-page-calendar-day-badge-size": "calc(var(--var-spacing-base) * 2)",
    "--var-page-calendar-gutter-width": "calc(var(--var-spacing-base) * 3.75)",
    "--var-page-calendar-side-padding-inline": "calc(var(--var-spacing-base) * 1)",
    "--var-page-calendar-detail-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-page-calendar-detail-padding": "calc(var(--var-spacing-base) * 0.75)",
    "--var-page-calendar-weekday-padding-block": "calc( var(--var-spacing-base) * 0.5 )",
    "--var-page-calendar-cell-min-block-size": "calc(var(--var-spacing-base) * 8)",
    "--var-page-calendar-cell-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-page-calendar-cell-padding": "calc(var(--var-spacing-base) * 0.5)",
    "--var-page-calendar-month-badge-size": "calc(var(--var-spacing-base) * 1.5)",
    "--var-page-calendar-week-badge-size": "calc(var(--var-spacing-base) * 1.5)",
    "--var-page-calendar-hour-label-inset-block-start": "calc( var(--var-spacing-base) * -0.625 )",
    "--var-page-calendar-hour-label-inset-inline-end": "calc( var(--var-spacing-base) * 0.5 )",
    "--var-page-calendar-pill-radius": "calc(var(--var-radius, var(--var-radius-base)) / 3)",
    "--var-page-calendar-pill-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
    "--var-page-calendar-pill-block-size": "calc(var(--var-spacing-base) * 1.25)",
    "--var-page-calendar-cell-gap-tight": "calc(var(--var-spacing-base) * 0.125)",
    "--var-table-rounded": "calc(var(--var-radius, var(--var-radius-base)) * 0.666667)",
    "--var-table-groups-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-table-group-title-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-table-group-title-padding-block": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-group-title-padding-inline": "calc(var(--var-spacing-base) * 0.75)",
    "--var-table-inline-gap-tight": "calc(var(--var-spacing-base) * 0.25)",
    "--var-table-filter-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-table-filter-icon-size": "calc(var(--var-spacing-base) * 0.875)",
    "--var-table-filter-delete-icon-size": "calc(var(--var-spacing-base) * 1)",
    "--var-table-filter-list-margin-block-start": "calc(var(--var-spacing-base) * 1)",
    "--var-table-filter-list-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-filter-row-gap": "calc(var(--var-spacing-base) * 0.75)",
    "--var-table-filter-delete-control-margin-block-start": "calc( var(--var-spacing-base) * 1.25 )",
    "--var-table-filter-inline-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-table-filter-inline-padding-block": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-filter-inline-delete-margin-block-start": "calc( var(--var-spacing-base) * 1 )",
    "--var-table-group-icon-size": "calc(var(--var-spacing-base) * 0.875)",
    "--var-table-group-delete-icon-size": "calc(var(--var-spacing-base) * 1)",
    "--var-table-group-order-list-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-sort-icon-size": "calc(var(--var-spacing-base) * 0.875)",
    "--var-table-sort-list-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-sort-row-gap": "calc(var(--var-spacing-base) * 0.75)",
    "--var-table-groups-margin-block-start": "calc(var(--var-spacing-base) * 1)",
    "--var-table-groups-margin-block": "calc(var(--var-spacing-base) * 1)",
    "--var-table-row-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-table-row-padding-block-end": "calc(var(--var-spacing-base) * 1)",
    "--var-table-cell-padding": "calc(var(--var-spacing-base) * 0.75)",
    "--var-table-cell-padding-inline": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-head-icon-size": "calc(var(--var-spacing-base) * 0.875)",
    "--var-table-head-cell-block-size": "calc(var(--var-spacing-base) * 3.5)",
    "--var-table-head-filter-item-margin-block": "calc( var(--var-spacing-base) * 0.25 )",
    "--var-table-properties-icon-size": "calc(var(--var-spacing-base) * 0.875)",
    "--var-table-properties-trigger-min-block-size": "calc( var(--var-spacing-base) * 2.75 )",
    "--var-table-properties-list-min-inline-size": "calc( var(--var-spacing-base) * 14 )",
    "--var-table-properties-list-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-properties-item-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-properties-handle-padding": "calc(var(--var-spacing-base) * 0.25)",
    "--var-table-divider-width": "calc(var(--var-spacing-base) * 1)",
    "--var-table-divider-width-active": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-resizer-inline-size": "calc(var(--var-spacing-base) * 0.75)",
    "--var-table-resizer-block-size": "calc(var(--var-spacing-base) * 3)",
    "--var-table-resizer-focus-ring-offset": "calc(var(--var-spacing-base) * 0.125)",
    "--var-table-pagination-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-table-pagination-padding": "calc(var(--var-spacing-base) * 0.75)",
    "--var-table-pagination-items-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-pagination-item-padding-inline": "calc( var(--var-spacing-base) * 0.75 )",
    "--var-table-pagination-item-padding-block": "calc( var(--var-spacing-base) * 0.25 )",
    "--var-table-metadata-margin-block-end": "calc(var(--var-spacing-base) * 0.25)",
    "--var-table-metadata-gap-inline": "calc(var(--var-spacing-base) * 1)",
    "--var-table-metadata-gap-block": "calc(var(--var-spacing-base) * 0.25)",
    "--var-table-operations-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-table-operations-padding-block": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-pill-radius": "calc(var(--var-radius, var(--var-radius-base)) * 1)",
    "--var-table-pill-padding-inline": "calc(var(--var-spacing-base) * 1)",
    "--var-table-pill-padding-block": "calc(var(--var-spacing-base) * 0.125)",
    "--var-table-filter-dot-size": "calc(var(--var-spacing-base) * 0.75)",
    "--var-table-filter-dot-margin-inline-end": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-loading-block-size": "calc(var(--var-spacing-base) * 3.5)",
    "--var-table-loading-bar-block-size": "calc(var(--var-spacing-base) * 0.5)",
    "--var-table-loading-bar-radius": "calc(var(--var-radius, var(--var-radius-base)) / 3)",
    "--var-table-empty-block-size": "calc(var(--var-spacing-base) * 12)",
    "--var-table-scroll-sentinel-block-size": "calc(var(--var-spacing-base) * 0.125)",
    "--var-shortcut-content-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-shortcut-icon-size": "calc(var(--var-spacing-base) * 0.75)",
    "--var-wizard-surface-inline-size": "calc(var(--var-spacing-base) * 20)",
    "--var-wizard-surface-max-inline-size": "calc(var(--var-spacing-base) * 24)",
    "--var-wizard-surface-gap": "calc(var(--var-spacing-base) * 0.75)",
    "--var-wizard-surface-radius": "calc( var(--var-radius, 0px) + calc(var(--var-radius-base) / 2) )",
    "--var-wizard-surface-padding": "calc(var(--var-spacing-base) * 1)",
    "--var-wizard-footer-padding-block-start": "calc(var(--var-spacing-base) * 0.5)",
    "--var-wizard-actions-gap": "calc(var(--var-spacing-base) * 0.5)",
    "--var-wizard-counter-inset-inline-end": "calc(var(--var-spacing-base) * 0.5)",
    "--var-wizard-counter-inset-block-start": "calc(var(--var-spacing-base) * 0.5)",
    "--var-wizard-focus-outline-width": "calc(var(--var-spacing-base) * 0.125)",
    "--var-wizard-focus-outline-offset": "calc(var(--var-spacing-base) * 0.125)",
    "--var-skeleton-radius": "calc(var(--var-radius, var(--var-radius-base)) / 3)",
    "--var-skeleton-cell-block-size": "calc(var(--var-spacing-base) * 1.5)",
    "--var-skeleton-block-size": "calc(var(--var-spacing-base) * 2)",
    "--var-skeleton-block-inline-size": "calc(var(--var-spacing-base) * 8)",
    "--var-skeleton-list-gap": "calc(var(--var-spacing-base) * 1.5)",
    "--var-stats-rounded": "calc(var(--var-radius-base) * 1)",
    "--var-stats-p": "calc(var(--var-spacing-base) * 1.5)",
    "--var-stats-gap": "calc(var(--var-spacing-base) * 1)",
    "--var-stats-icon-size": "calc(var(--var-spacing-base) * 2.5)",
    "--var-stats-icon-p": "calc(var(--var-spacing-base) * 2)",
    "--var-stats-inner-gap": "calc(var(--var-spacing-base) * 0.25)",
    "--var-stats-footer-px": "calc(var(--var-spacing-base) * 1.5)",
    "--var-stats-footer-py": "calc(var(--var-spacing-base) * 0.5)",
} as const;

export const geometryToken = (name: string): string => {
    const key = `--var-${name}`;
    const fallback = defaultGeometryTokens[key as keyof typeof defaultGeometryTokens];
    return fallback ? `var(${key}, ${fallback})` : `var(${key})`;
};
