import { type TokenRemap } from "@g4rcez/components";
import { createTokenStyles } from "@g4rcez/components/styles";
import { defaultDarkTheme } from "@g4rcez/components/themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const tokenRemap: TokenRemap = {
    colors: (t) => {
        t.value = t.value.replace("hsla(", "").replace(/\)$/, "");
        return t;
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const stylesDark = createTokenStyles(defaultDarkTheme, {
        ...tokenRemap,
        name: "dark",
    });
    return (
        <html lang="en" className="dark">
            <head>
                <style>{stylesDark}</style>
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
        </html>
    );
}
