import { defineComponentStyles } from "../../../lib/component-styles";

export const fileUploadStyles = defineComponentStyles({
    name: "file-upload",
    css: "@g4rcez/components/file-upload.css",
    variants: {},
    defaults: {},
    slots: [
        "accent",
        "actions",
        "aside",
        "column",
        "dropzone",
        "file-details",
        "file-icon",
        "file-row",
        "idle",
        "idle-copy",
        "idle-icon",
        "idle-icon-wrap",
        "item",
        "list",
        "preview-button",
        "preview-image",
        "remove-button",
        "remove-icon",
        "row",
        "size",
        "stack",
        "thumb-icon",
        "viewer-image",
        "viewer-name",
        "viewer-size",
        "viewer-video",
    ],
    dependencies: ["modal"],
});
