import { resolve } from "node:path";
import { defineConfig } from "vite";

const root = import.meta.dirname;

export default defineConfig({
    css: {
        devSourcemap: true,
    },
    build: {
        outDir: "./dist",
        emptyOutDir: false,
        sourcemap: true,
        cssCodeSplit: true,
        cssMinify: true,
        rollupOptions: {
            input: {
                tokens: resolve(root, "src/styles/tokens.css"),
                base: resolve(root, "src/styles/base.css"),
                foundation: resolve(root, "src/styles/foundation.css"),
                tag: resolve(root, "src/components/core/tag.css"),
                form: resolve(root, "src/components/form/form.css"),
                input: resolve(root, "src/components/form/input.css"),
                select: resolve(root, "src/components/form/select.css"),
                slider: resolve(root, "src/components/form/slider.css"),
                switch: resolve(root, "src/components/form/switch.css"),
                table: resolve(root, "src/components/table/table.css"),
                card: resolve(root, "src/components/display/card.css"),
                list: resolve(root, "src/components/display/list.css"),
                step: resolve(root, "src/components/display/step.css"),
                tabs: resolve(root, "src/components/display/tabs.css"),
                alert: resolve(root, "src/components/display/alert.css"),
                empty: resolve(root, "src/components/display/empty.css"),
                stats: resolve(root, "src/components/display/stats.css"),
                menu: resolve(root, "src/components/floating/menu.css"),
                checkbox: resolve(root, "src/components/form/checkbox.css"),
                radiobox: resolve(root, "src/components/form/radiobox.css"),
                textarea: resolve(root, "src/components/form/textarea.css"),
                "page-calendar": resolve(root, "src/components/page-calendar/page-calendar.css"),
                polymorph: resolve(root, "src/components/core/polymorph.css"),
                modal: resolve(root, "src/components/floating/modal.css"),
                "task-list": resolve(root, "src/components/form/task-list.css"),
                typography: resolve(root, "src/components/core/typography.css"),
                masonry: resolve(root, "src/components/display/masonry.css"),
                spinner: resolve(root, "src/components/display/spinner.css"),
                expand: resolve(root, "src/components/floating/expand.css"),
                wizard: resolve(root, "src/components/floating/wizard.css"),
                calendar: resolve(root, "src/components/display/calendar.css"),
                progress: resolve(root, "src/components/display/progress.css"),
                timeline: resolve(root, "src/components/display/timeline.css"),
                toolbar: resolve(root, "src/components/floating/toolbar.css"),
                tooltip: resolve(root, "src/components/floating/tooltip.css"),
                "date-picker": resolve(root, "src/components/form/date-picker.css"),
                "file-upload": resolve(root, "src/components/form/file-upload.css"),
                "input-field": resolve(root, "src/components/form/input-field.css"),
                dropdown: resolve(root, "src/components/floating/dropdown.css"),
                autocomplete: resolve(root, "src/components/form/autocomplete.css"),
                "multi-select": resolve(root, "src/components/form/multi-select.css"),
                "render-on-view": resolve(root, "src/components/core/render-on-view.css"),
                notifications: resolve(root, "src/components/display/notifications.css"),
                "command-palette": resolve(root, "src/components/floating/command-palette.css"),
                button: resolve(root, "src/components/core/button.css"),
                heading: resolve(root, "src/components/core/heading.css"),
                resizable: resolve(root, "src/components/core/resizable.css"),
                shortcut: resolve(root, "src/components/display/shortcut.css"),
                skeleton: resolve(root, "src/components/display/skeleton.css"),
                "free-text": resolve(root, "src/components/form/free-text.css"),
                "page-calendar-header": resolve(root, "src/components/page-calendar/calendar-header.css"),
                "page-calendar-day-view": resolve(root, "src/components/page-calendar/day-view.css"),
                "page-calendar-event-pill": resolve(root, "src/components/page-calendar/event-pill.css"),
                "page-calendar-month-view": resolve(root, "src/components/page-calendar/month-view.css"),
                "page-calendar-week-view": resolve(root, "src/components/page-calendar/week-view.css"),
                "table-filter": resolve(root, "src/components/table/filter.css"),
                "table-group": resolve(root, "src/components/table/group.css"),
                "table-root": resolve(root, "src/components/table/index.css"),
                "table-inner-table": resolve(root, "src/components/table/inner-table.css"),
                "table-metadata": resolve(root, "src/components/table/metadata.css"),
                "table-pagination": resolve(root, "src/components/table/pagination.css"),
                "table-row": resolve(root, "src/components/table/row.css"),
                "table-sort": resolve(root, "src/components/table/sort.css"),
                "table-head": resolve(root, "src/components/table/thead.css"),
                index: resolve(root, "src/styles/index.v6.css"),
            },
            output: {
                entryFileNames: "css-entry-[name].js",
                chunkFileNames: "css-entry-[name]-[hash].js",
                assetFileNames: (assetInfo) => {
                    const name = assetInfo.names?.[0] ?? assetInfo.name ?? "asset";
                    if (name.endsWith(".css")) return "[name][extname]";
                    if (name.endsWith(".css.map")) return "[name][extname]";
                    return "assets/[name]-[hash][extname]";
                },
            },
        },
    },
});
