import { defineComponentStyles } from "../../../lib/component-styles";

export const inputFieldStyles = defineComponentStyles({
    name: "input-field",
    variants: {
        size: ["normal", "small"],
    },
    css: "@g4rcez/components/input.css",
    defaults: {
        size: "normal",
    },
    slots: [
        "border",
        "control",
        "control-disabled",
        "control-state",
        "control-surface",
        "error",
        "error-state",
        "error-text",
        "feedback",
        "feedback-body",
        "feedback-hidden",
        "feedback-icon",
        "feedback-state",
        "feedback-text",
        "fieldset",
        "label",
        "label-active",
        "label-disabled",
        "label-layout",
        "label-meta",
        "label-row",
        "label-state",
        "optional",
        "optional-state",
        "optional-text",
        "slot",
        "slot-end",
        "slot-start",
        "sr-only",
        "status",
        "status-error",
        "status-icon",
        "status-indicator",
        "status-success",
        "tooltip-body",
        "tooltip-content",
        "tooltip-icon",
        "tooltip-trigger",
    ],
    dependencies: ["polymorph", "tooltip"],
});
