import { defineComponentStyles } from "../../lib/component-styles";

export const tableHeadStyles = defineComponentStyles({
    name: "table-head",
    variants: {},
    css: "@g4rcez/components/table.css",
    defaults: {},
    slots: [
        "filter-icon",
        "add-icon",
        "properties-trigger",
        "properties-trigger-content",
        "properties-trigger-icon",
        "properties-list",
        "properties-item",
        "properties-drag-handle",
        "properties-drag-icon",
        "properties-label",
        "cell",
        "cell-content",
        "actions",
        "sr-label",
        "dropdown-title",
        "title-strong",
        "filter-list",
        "filter-item",
        "add-filter-button",
        "label",
        "resizer",
    ],
    dependencies: ["checkbox", "dropdown", "table-filter", "table-sort"],
});
