import { defineComponentStyles } from "../../../lib/component-styles";

export const datePickerStyles = defineComponentStyles({
    name: "date-picker",
    css: "@g4rcez/components/date-picker.css",
    variants: {},
    defaults: {},
    slots: [
        "calendar-icon",
        "sr-label",
        "range-calendar",
        "range-header",
        "range-nights",
        "range-fields",
        "range-field",
        "range-header-field",
        "range-header-field-label",
        "range-header-field-value",
        "range-header-field-divider",
        "range-control",
        "range-input",
        "range-separator",
        "panel",
        "presets",
        "preset-list",
        "preset-button",
        "actions",
        "actions-confirm",
        "today-action",
        "cancel-action",
        "apply-action",
    ],
    dependencies: ["calendar", "dropdown", "input"],
});
