import { defineComponentStyles } from "../../../lib/component-styles";

export const multiSelectStyles = defineComponentStyles({
    name: "multi-select",
    css: "@g4rcez/components/multi-select.css",
    variants: {
        size: ["normal", "small"],
    },
    defaults: {
        size: "normal",
    },
    slots: [
        "action",
        "actions",
        "caret-icon",
        "checkbox",
        "control-state",
        "empty",
        "empty-text",
        "footer",
        "input",
        "invalid",
        "item",
        "list",
        "option",
        "overlay",
        "overflow",
        "panel",
        "placeholder",
        "placeholder-text",
        "results",
        "scroll",
        "search",
        "sr-label",
        "surface",
        "tag-remove",
        "tag-remove-icon",
        "tags",
        "transition",
        "value",
    ],
    dependencies: ["free-text", "select", "tag"],
});
